export type HustleCategory =
  | "SNS·콘텐츠"
  | "제휴마케팅"
  | "재능판매"
  | "온라인강의"
  | "쇼핑몰·판매"
  | "리셀"
  | "앱테크·설문"
  | "투자"
  | "배달·서비스"
  | "디지털콘텐츠"
  | "기타";

export interface SideHustle {
  id: string;
  name: string;
  emoji: string;
  category: HustleCategory;
  oneline: string;
  description: string;
  incomeRange: string;
  startupCost: string;
  timeToFirst: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  officialUrl?: string;
  isHot?: boolean;
  isNew?: boolean;
}

export const HUSTLE_CATEGORIES: HustleCategory[] = [
  "SNS·콘텐츠",
  "제휴마케팅",
  "재능판매",
  "온라인강의",
  "쇼핑몰·판매",
  "리셀",
  "앱테크·설문",
  "투자",
  "배달·서비스",
  "디지털콘텐츠",
  "기타",
];

export const CATEGORY_EMOJI: Record<HustleCategory, string> = {
  "SNS·콘텐츠": "📱",
  "제휴마케팅": "🔗",
  "재능판매": "💼",
  "온라인강의": "🎓",
  "쇼핑몰·판매": "🛒",
  "리셀": "👟",
  "앱테크·설문": "📲",
  "투자": "📈",
  "배달·서비스": "🛵",
  "디지털콘텐츠": "💾",
  "기타": "✨",
};

export const ALL_HUSTLES: SideHustle[] = [
  // ─────────────────────────────────────────
  // SNS·콘텐츠
  // ─────────────────────────────────────────
  {
    id: "youtube",
    name: "유튜브 채널 운영",
    emoji: "🎬",
    category: "SNS·콘텐츠",
    oneline: "영상 콘텐츠로 광고·협찬 수익",
    description: "유튜브에 채널을 개설하고 영상을 올려 구독자를 모으면 광고 수익, 협찬, 멤버십 등 다양한 방식으로 수익을 낼 수 있다. 초기 성장은 느리지만 채널이 성장하면 자동 수익이 가능하다.",
    incomeRange: "월 0 ~ 500만원+",
    startupCost: "무료 (장비 선택)",
    timeToFirst: "6개월~1년",
    difficulty: 5,
    officialUrl: "https://www.youtube.com",
    isHot: true,
  },
  {
    id: "youtube-shorts",
    name: "유튜브 쇼츠",
    emoji: "🎞️",
    category: "SNS·콘텐츠",
    oneline: "60초 이하 쇼츠로 빠른 성장",
    description: "짧은 세로형 영상으로 알고리즘 노출 기회가 롱폼보다 훨씬 많다. 제작 시간이 짧지만 광고 수익은 낮은 편. 채널 성장 후 롱폼으로 전환 전략이 일반적이다.",
    incomeRange: "월 0 ~ 50만원",
    startupCost: "무료",
    timeToFirst: "3~6개월",
    difficulty: 3,
    officialUrl: "https://www.youtube.com/shorts",
  },
  {
    id: "tiktok",
    name: "틱톡 크리에이터",
    emoji: "🎵",
    category: "SNS·콘텐츠",
    oneline: "틱톡 팔로워로 광고·협찬 수익",
    description: "10~60초 영상으로 팔로워를 빠르게 모을 수 있다. 틱톡 자체 수익 프로그램과 협찬 광고가 주요 수익원. 한국보다 해외 팔로워가 많으면 수익이 더 높다.",
    incomeRange: "월 0 ~ 200만원",
    startupCost: "무료",
    timeToFirst: "3~6개월",
    difficulty: 3,
    officialUrl: "https://www.tiktok.com",
    isHot: true,
  },
  {
    id: "instagram-sponsor",
    name: "인스타그램 협찬·광고",
    emoji: "📸",
    category: "SNS·콘텐츠",
    oneline: "팔로워 기반 브랜드 협찬 수익",
    description: "팔로워 1만 명 이상이면 협찬 광고 제안이 들어오기 시작한다. 팔로워 수보다 참여율(좋아요·댓글 비율)이 더 중요하다. 패션·뷰티·음식 분야가 협찬 단가 높다.",
    incomeRange: "건당 5~500만원",
    startupCost: "무료",
    timeToFirst: "6개월~1년",
    difficulty: 4,
    officialUrl: "https://www.instagram.com",
  },
  {
    id: "naver-influencer",
    name: "네이버 인플루언서",
    emoji: "🟢",
    category: "SNS·콘텐츠",
    oneline: "네이버 인플루언서 선정 후 광고 수익",
    description: "네이버 인플루언서로 선정되면 블로그·포스트·숏클립 등에 광고가 붙어 수익이 발생한다. 키워드 챌린지, 팬심 등 네이버 생태계 내 다양한 수익 채널이 있다.",
    incomeRange: "월 10~200만원",
    startupCost: "무료",
    timeToFirst: "3~6개월",
    difficulty: 3,
    officialUrl: "https://in.naver.com",
  },
  {
    id: "naver-blog",
    name: "네이버 블로그 (애드포스트)",
    emoji: "📝",
    category: "SNS·콘텐츠",
    oneline: "정보성 글로 광고 수익 + 체험단",
    description: "검색 유입이 높은 키워드로 포스팅하면 애드포스트 광고 수익이 발생한다. 체험단, 원고료, 협찬 등 부가 수익도 크다. 꾸준한 포스팅이 핵심.",
    incomeRange: "월 5~100만원",
    startupCost: "무료",
    timeToFirst: "3~6개월",
    difficulty: 2,
    officialUrl: "https://blog.naver.com",
    isHot: true,
  },
  {
    id: "tistory",
    name: "티스토리 블로그 (구글 애드센스)",
    emoji: "✍️",
    category: "SNS·콘텐츠",
    oneline: "구글 애드센스 연동으로 광고 수익",
    description: "네이버 블로그보다 광고 단가가 높은 구글 애드센스를 붙일 수 있다. SEO 최적화로 구글 검색 유입을 높이는 것이 핵심. 승인까지 시간이 걸리고 초기 트래픽 쌓기가 관건.",
    incomeRange: "월 0~150만원",
    startupCost: "무료",
    timeToFirst: "6개월~1년",
    difficulty: 3,
    officialUrl: "https://www.tistory.com",
  },
  {
    id: "kakao-view",
    name: "카카오뷰",
    emoji: "💛",
    category: "SNS·콘텐츠",
    oneline: "카카오 플랫폼 콘텐츠 큐레이션 수익",
    description: "카카오뷰 채널을 개설해 콘텐츠를 큐레이션하면 구독자 수에 따라 수익이 발생한다. 진입장벽이 낮지만 수익 규모도 낮은 편.",
    incomeRange: "월 0~30만원",
    startupCost: "무료",
    timeToFirst: "1~3개월",
    difficulty: 1,
    officialUrl: "https://view.kakao.com",
  },
  {
    id: "brunch",
    name: "브런치 작가",
    emoji: "📖",
    category: "SNS·콘텐츠",
    oneline: "글쓰기로 작가 브랜딩 + 수익화",
    description: "카카오 브런치에서 작가 신청 후 글을 연재하면 책 출판, 강의, 원고 의뢰 등의 기회가 생긴다. 직접 광고 수익은 없지만 부가 수익 가능성이 높다.",
    incomeRange: "부가 수익",
    startupCost: "무료",
    timeToFirst: "6개월+",
    difficulty: 2,
    officialUrl: "https://brunch.co.kr",
  },
  {
    id: "newsletter",
    name: "뉴스레터 (서브스택·스티비)",
    emoji: "📧",
    category: "SNS·콘텐츠",
    oneline: "구독자에게 유료 뉴스레터 발송",
    description: "특정 분야의 전문 지식을 담은 뉴스레터를 발행해 유료 구독 수익을 낸다. 서브스택(해외)이나 스티비(국내)를 활용. 충성 구독자가 생기면 안정적인 월정액 수익 가능.",
    incomeRange: "월 0~300만원",
    startupCost: "무료",
    timeToFirst: "3~12개월",
    difficulty: 3,
    isNew: true,
  },
  {
    id: "threads",
    name: "스레드 (Threads) 운영",
    emoji: "🧵",
    category: "SNS·콘텐츠",
    oneline: "메타 스레드로 팔로워 확보 후 수익화",
    description: "인스타그램 연동으로 빠른 성장이 가능한 메타의 텍스트 기반 SNS. 아직 광고 수익화 시스템이 초기 단계라 협찬이나 본인 상품 홍보 채널로 주로 활용된다.",
    incomeRange: "협찬 수익",
    startupCost: "무료",
    timeToFirst: "3~6개월",
    difficulty: 2,
    isNew: true,
  },

  // ─────────────────────────────────────────
  // 제휴마케팅
  // ─────────────────────────────────────────
  {
    id: "coupang-partners",
    name: "쿠팡파트너스",
    emoji: "🛍️",
    category: "제휴마케팅",
    oneline: "쿠팡 링크 공유로 구매 수수료 수익",
    description: "쿠팡파트너스에 가입해 상품 링크를 블로그·SNS에 공유하면 클릭 후 구매 시 3~15% 수수료를 받는다. 트래픽이 있는 채널이 있으면 가장 진입이 쉬운 부업 중 하나.",
    incomeRange: "월 1~500만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 1,
    officialUrl: "https://partners.coupang.com",
    isHot: true,
  },
  {
    id: "linkprice",
    name: "링크프라이스",
    emoji: "🔗",
    category: "제휴마케팅",
    oneline: "국내 최대 제휴마케팅 플랫폼",
    description: "링크프라이스는 국내 다양한 쇼핑몰과 서비스의 제휴마케팅을 중개한다. 쿠팡 외 다양한 브랜드 링크로 수익 다각화 가능.",
    incomeRange: "월 1~100만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 2,
    officialUrl: "https://www.linkprice.com",
  },
  {
    id: "tenping",
    name: "텐핑",
    emoji: "💸",
    category: "제휴마케팅",
    oneline: "SNS 공유만으로 수수료 수익",
    description: "텐핑은 SNS에 광고 콘텐츠를 공유하면 성과에 따라 수익을 주는 플랫폼. 팔로워가 많을수록 유리하며 간편하게 시작할 수 있다.",
    incomeRange: "월 1~50만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 1,
    officialUrl: "https://www.tenping.kr",
  },
  {
    id: "amazon-associates",
    name: "아마존 어소시에이트",
    emoji: "📦",
    category: "제휴마케팅",
    oneline: "아마존 링크로 해외 수수료 수익",
    description: "아마존의 공식 제휴마케팅 프로그램. 영어 블로그나 해외 대상 콘텐츠를 운영하면 달러로 수익을 올릴 수 있다. 국내 대상 채널보다 단가가 높다.",
    incomeRange: "월 1~200만원",
    startupCost: "무료",
    timeToFirst: "1~3개월",
    difficulty: 3,
    officialUrl: "https://affiliate-program.amazon.com",
  },
  {
    id: "ilikepick",
    name: "아이라이크픽",
    emoji: "🎯",
    category: "제휴마케팅",
    oneline: "SNS 마케터 활동으로 수익",
    description: "아이라이크픽에서 SNS 마케터로 활동하면 다양한 캠페인에 참여해 수익을 올릴 수 있다. 블로그나 SNS 채널이 있으면 바로 시작 가능.",
    incomeRange: "월 5~50만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 1,
    officialUrl: "https://www.ilikepick.com",
  },

  // ─────────────────────────────────────────
  // 재능판매 / 프리랜서
  // ─────────────────────────────────────────
  {
    id: "kmong",
    name: "크몽",
    emoji: "💼",
    category: "재능판매",
    oneline: "국내 1위 재능마켓에서 서비스 판매",
    description: "디자인, 개발, 번역, 마케팅, 영상편집 등 다양한 서비스를 판매할 수 있는 국내 최대 재능마켓. 전문가 등록 후 서비스를 올리면 구매 요청이 들어온다.",
    incomeRange: "월 10~500만원",
    startupCost: "무료",
    timeToFirst: "1~4주",
    difficulty: 3,
    officialUrl: "https://kmong.com",
    isHot: true,
  },
  {
    id: "soomgo",
    name: "숨고",
    emoji: "🤝",
    category: "재능판매",
    oneline: "전문가 매칭 플랫폼에서 서비스 판매",
    description: "레슨, 과외, 인테리어, 이사, 촬영 등 오프라인 서비스도 포함하는 전문가 매칭 플랫폼. 견적 요청이 오면 제안서를 보내는 방식으로 운영된다.",
    incomeRange: "월 10~300만원",
    startupCost: "무료",
    timeToFirst: "1~2주",
    difficulty: 2,
    officialUrl: "https://soomgo.com",
  },
  {
    id: "wishket",
    name: "위시켓",
    emoji: "💻",
    category: "재능판매",
    oneline: "IT 프리랜서 전문 프로젝트 매칭",
    description: "개발, 디자인, 기획 등 IT 분야 프리랜서를 위한 전문 플랫폼. 단가가 높고 장기 프로젝트도 많다. IT 관련 포트폴리오가 있어야 수주 가능.",
    incomeRange: "프로젝트당 100~3000만원",
    startupCost: "무료",
    timeToFirst: "1~4주",
    difficulty: 4,
    officialUrl: "https://www.wishket.com",
  },
  {
    id: "freemoa",
    name: "프리모아",
    emoji: "🖥️",
    category: "재능판매",
    oneline: "IT 프리랜서 전문 플랫폼",
    description: "위시켓과 유사한 IT 프리랜서 플랫폼. 개발·디자인 단기 프로젝트가 많고, 원격 근무 가능한 프로젝트도 많다.",
    incomeRange: "프로젝트당 50~2000만원",
    startupCost: "무료",
    timeToFirst: "1~4주",
    difficulty: 4,
    officialUrl: "https://www.freemoa.net",
  },
  {
    id: "upwork",
    name: "업워크 (해외 프리랜서)",
    emoji: "🌍",
    category: "재능판매",
    oneline: "해외 클라이언트 상대 달러 수입",
    description: "세계 최대 프리랜서 플랫폼. 영어 실력과 전문 스킬이 있다면 국내보다 훨씬 높은 단가를 받을 수 있다. 경쟁이 치열하므로 포트폴리오와 리뷰 관리가 중요.",
    incomeRange: "시간당 $10~$100",
    startupCost: "무료",
    timeToFirst: "1~3개월",
    difficulty: 5,
    officialUrl: "https://www.upwork.com",
  },

  // ─────────────────────────────────────────
  // 온라인강의 / 컨설팅
  // ─────────────────────────────────────────
  {
    id: "class101",
    name: "클래스101",
    emoji: "🎨",
    category: "온라인강의",
    oneline: "취미·기술 강의 판매로 패시브 인컴",
    description: "한 번 강의를 제작해 올리면 지속적으로 수익이 발생하는 패시브 인컴 플랫폼. 크래프트, 드로잉, 요리, 개발 등 다양한 분야 강의를 판매할 수 있다.",
    incomeRange: "월 10~500만원",
    startupCost: "장비 비용",
    timeToFirst: "강의 제작 후",
    difficulty: 3,
    officialUrl: "https://class101.net",
    isHot: true,
  },
  {
    id: "taling",
    name: "탈잉",
    emoji: "📚",
    category: "온라인강의",
    oneline: "재능 공유 플랫폼에서 튜터 활동",
    description: "오프라인·온라인 강의를 모두 등록할 수 있는 튜터링 플랫폼. 초기 수강생 모집이 어렵지만 리뷰가 쌓이면 안정적인 수입이 가능.",
    incomeRange: "월 10~200만원",
    startupCost: "무료",
    timeToFirst: "1~3개월",
    difficulty: 3,
    officialUrl: "https://taling.me",
  },
  {
    id: "online-tutoring",
    name: "온라인 과외 (과외앱)",
    emoji: "🧑‍🏫",
    category: "온라인강의",
    oneline: "학생 대상 비대면 과외 수업",
    description: "아이캔, 과외닷컴, 수학의민족 등 과외 앱을 통해 학생을 구한다. 수능·어학·코딩 등 다양한 분야 가능. 시간당 3~10만원으로 단가가 높은 편.",
    incomeRange: "월 20~200만원",
    startupCost: "무료",
    timeToFirst: "1~2주",
    difficulty: 2,
  },
  {
    id: "udemy",
    name: "유데미 (Udemy) 강의 등록",
    emoji: "🌐",
    category: "온라인강의",
    oneline: "글로벌 강의 플랫폼에 영상 강의 등록",
    description: "전 세계 사용자가 있는 유데미에 강의를 올리면 달러 수익을 올릴 수 있다. 한국어 강의도 가능하고, 할인 판매 정책이 있어 단가는 낮지만 글로벌 수요가 있다.",
    incomeRange: "월 5~300만원",
    startupCost: "무료",
    timeToFirst: "강의 제작 후",
    difficulty: 3,
    officialUrl: "https://www.udemy.com",
  },

  // ─────────────────────────────────────────
  // 쇼핑몰·판매
  // ─────────────────────────────────────────
  {
    id: "smart-store",
    name: "스마트스토어",
    emoji: "🛒",
    category: "쇼핑몰·판매",
    oneline: "네이버 스마트스토어로 온라인 쇼핑몰 창업",
    description: "네이버 스마트스토어는 국내에서 가장 접근하기 쉬운 온라인 쇼핑몰 플랫폼. 위탁판매로 재고 없이 시작하거나, 직접 소싱해 판매할 수 있다.",
    incomeRange: "월 0~1000만원+",
    startupCost: "소액~수백만원",
    timeToFirst: "2~8주",
    difficulty: 3,
    officialUrl: "https://sell.smartstore.naver.com",
    isHot: true,
  },
  {
    id: "coupang-rocket",
    name: "쿠팡 로켓그로스",
    emoji: "🚀",
    category: "쇼핑몰·판매",
    oneline: "쿠팡 물류망을 활용한 판매",
    description: "쿠팡의 로켓배송 인프라를 활용해 상품을 판매하는 방식. CS와 배송을 쿠팡이 담당해 운영이 간편하지만 수수료가 높다.",
    incomeRange: "월 0~500만원",
    startupCost: "재고 비용",
    timeToFirst: "2~4주",
    difficulty: 3,
    officialUrl: "https://wing.coupang.com",
  },
  {
    id: "ably-seller",
    name: "에이블리 셀러",
    emoji: "👗",
    category: "쇼핑몰·판매",
    oneline: "여성 패션 앱 에이블리에서 의류 판매",
    description: "여성 패션 특화 앱 에이블리에 입점해 의류, 액세서리를 판매한다. 고정 고객층이 있어 진입 후 안정적인 매출이 가능하다.",
    incomeRange: "월 0~300만원",
    startupCost: "재고 비용",
    timeToFirst: "2~4주",
    difficulty: 3,
    officialUrl: "https://seller.a-bly.com",
  },
  {
    id: "amazon-fba",
    name: "아마존 FBA",
    emoji: "📦",
    category: "쇼핑몰·판매",
    oneline: "아마존 물류로 해외 쇼핑몰 운영",
    description: "아마존의 물류 센터에 재고를 보내고 판매 시 아마존이 배송과 CS를 처리해 주는 구조. 달러 수익 가능하지만 초기 재고 투자와 학습이 필요하다.",
    incomeRange: "월 0~1000만원+",
    startupCost: "수백만원",
    timeToFirst: "1~3개월",
    difficulty: 5,
    officialUrl: "https://sell.amazon.com",
  },
  {
    id: "aliexpress-dropshipping",
    name: "알리 드롭쉬핑",
    emoji: "✈️",
    category: "쇼핑몰·판매",
    oneline: "재고 없이 알리익스프레스 상품 판매",
    description: "알리익스프레스 상품을 국내 쇼핑몰에 더 높은 가격으로 올려 주문이 들어오면 알리에서 직접 배송하는 방식. 재고 리스크가 없지만 배송 시간과 품질 이슈가 있다.",
    incomeRange: "월 0~200만원",
    startupCost: "소액",
    timeToFirst: "1~2주",
    difficulty: 3,
    officialUrl: "https://www.aliexpress.com",
  },
  {
    id: "instagram-shop",
    name: "인스타그램 쇼핑몰",
    emoji: "📱",
    category: "쇼핑몰·판매",
    oneline: "인스타 팔로워 기반 직접 판매",
    description: "인스타그램 계정을 키워 의류, 소품 등을 직접 판매하는 방식. 플랫폼 수수료가 낮고 브랜드 구축에 유리하다. 콘텐츠 제작 능력이 중요하다.",
    incomeRange: "월 0~300만원",
    startupCost: "소액",
    timeToFirst: "3~6개월",
    difficulty: 3,
  },
  {
    id: "musinsa-store",
    name: "무신사 스토어",
    emoji: "👕",
    category: "쇼핑몰·판매",
    oneline: "국내 1위 패션 플랫폼 무신사 입점",
    description: "무신사에 브랜드로 입점해 의류를 판매한다. 심사 과정이 있고 최소 물량 조건이 있지만 무신사 트래픽을 활용해 매출을 올릴 수 있다.",
    incomeRange: "월 0~수천만원",
    startupCost: "수백만원",
    timeToFirst: "1~3개월",
    difficulty: 5,
    officialUrl: "https://partners.musinsa.com",
  },

  // ─────────────────────────────────────────
  // 리셀
  // ─────────────────────────────────────────
  {
    id: "kream",
    name: "KREAM 스니커즈·의류 리셀",
    emoji: "👟",
    category: "리셀",
    oneline: "한정판 스니커즈·의류 리셀 거래",
    description: "나이키, 아디다스 등 한정판 제품을 발매가에 구매해 KREAM에서 프리미엄으로 판매한다. 시세 파악이 중요하고 재고 손실 리스크가 있다.",
    incomeRange: "건당 1~50만원",
    startupCost: "구매 자금 필요",
    timeToFirst: "즉시",
    difficulty: 3,
    officialUrl: "https://kream.co.kr",
    isHot: true,
  },
  {
    id: "bunjang-resell",
    name: "번개장터 리셀",
    emoji: "⚡",
    category: "리셀",
    oneline: "한정판·단종 제품 번개장터 리셀",
    description: "희소성 있는 제품을 구매해 번개장터에서 웃돈을 받고 판매한다. 포켓몬 카드, 피규어, 전자기기 등 다양한 품목이 가능하다.",
    incomeRange: "건당 1~30만원",
    startupCost: "구매 자금 필요",
    timeToFirst: "즉시",
    difficulty: 2,
    officialUrl: "https://bunjang.co.kr",
  },
  {
    id: "used-flip",
    name: "당근마켓 중고 플리핑",
    emoji: "🥕",
    category: "리셀",
    oneline: "싸게 사서 수리·세척 후 비싸게 재판매",
    description: "당근마켓에서 저렴한 중고 물건을 구매해 수리, 세척, 재포장 후 더 높은 가격에 판매하는 방식. 눈썰미와 제품 지식이 중요하다.",
    incomeRange: "월 10~100만원",
    startupCost: "소액",
    timeToFirst: "즉시",
    difficulty: 2,
    officialUrl: "https://www.daangn.com",
  },
  {
    id: "ticket-resell",
    name: "공연 티켓 리셀",
    emoji: "🎫",
    category: "리셀",
    oneline: "인기 공연·스포츠 티켓 리셀",
    description: "인기 아티스트 콘서트, 스포츠 경기 등의 티켓을 정가에 구매해 프리미엄을 붙여 재판매한다. 단 티켓 전매가 법적으로 제한되는 경우도 있으니 주의.",
    incomeRange: "건당 1~20만원",
    startupCost: "티켓 구매 자금",
    timeToFirst: "즉시",
    difficulty: 2,
  },
  {
    id: "pokemon-card",
    name: "포켓몬·트레이딩 카드 리셀",
    emoji: "🃏",
    category: "리셀",
    oneline: "포켓몬 카드 개봉·리셀",
    description: "포켓몬 카드 등 트레이딩 카드를 구매해 희귀 카드를 리셀하거나, 봉투를 개봉해 고가 카드를 판매하는 방식. 시세 파악이 중요.",
    incomeRange: "건당 1~100만원",
    startupCost: "소액~수십만원",
    timeToFirst: "즉시",
    difficulty: 3,
    isHot: true,
  },

  // ─────────────────────────────────────────
  // 앱테크·설문
  // ─────────────────────────────────────────
  {
    id: "cashslide",
    name: "캐시슬라이드·잠금화면 앱테크",
    emoji: "📲",
    category: "앱테크·설문",
    oneline: "폰 잠금화면으로 적립금 모으기",
    description: "캐시슬라이드, 버즈런처 등 잠금화면 광고 앱을 사용하면 소액의 적립금이 쌓인다. 수익은 적지만 스마트폰을 쓰면서 자동으로 모을 수 있다.",
    incomeRange: "월 1~5만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 1,
    officialUrl: "https://www.cashslide.co.kr",
  },
  {
    id: "panel-now",
    name: "패널나우·설문조사",
    emoji: "📋",
    category: "앱테크·설문",
    oneline: "온라인 설문 참여로 포인트 적립",
    description: "패널나우, 엠브레인, 서베이링크 등 설문 앱에서 설문에 참여하면 현금으로 바꿀 수 있는 포인트를 얻는다. 시간이 많지 않아도 자투리 시간 활용 가능.",
    incomeRange: "월 1~10만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 1,
    officialUrl: "https://panelnow.co.kr",
  },
  {
    id: "toss-benefit",
    name: "토스·금융앱 혜택 수익",
    emoji: "💙",
    category: "앱테크·설문",
    oneline: "토스·카카오페이 이벤트 및 금융 혜택 활용",
    description: "토스, 카카오페이 등 핀테크 앱의 이벤트, 만보기, 토스피드, 행운복권 등을 이용해 소액을 적립한다. 금융 상품 가입 추천으로 추가 수익도 가능.",
    incomeRange: "월 1~5만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 1,
  },
  {
    id: "data-labeling",
    name: "데이터 라벨링",
    emoji: "🏷️",
    category: "앱테크·설문",
    oneline: "AI 학습용 데이터 작업으로 수익",
    description: "크라우드웍스, 에이모 등의 플랫폼에서 이미지 분류, 텍스트 검수 등 AI 학습 데이터 작업을 하고 건당 수수료를 받는다. 누구나 시작 가능하지만 단가가 낮다.",
    incomeRange: "월 5~30만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 1,
    isNew: true,
  },
  {
    id: "app-testing",
    name: "앱·웹 테스트 (유저테스팅)",
    emoji: "🔍",
    category: "앱테크·설문",
    oneline: "앱·웹사이트 사용 후 피드백 제공",
    description: "유저테스팅, 테스트IO 등에서 앱이나 웹사이트를 사용하며 피드백을 주는 작업. 건당 1만~2만원 수준이며 영어 가능하면 해외 플랫폼도 가능.",
    incomeRange: "건당 1~3만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 1,
  },

  // ─────────────────────────────────────────
  // 투자
  // ─────────────────────────────────────────
  {
    id: "stock-dividend",
    name: "배당주 투자",
    emoji: "💰",
    category: "투자",
    oneline: "배당금으로 월수입 만들기",
    description: "삼성전자, 고배당 ETF 등 배당주에 투자해 분기·반기·연간 배당금을 받는다. 장기적으로 배당 재투자하면 복리 효과를 누릴 수 있다.",
    incomeRange: "연 2~8% 배당",
    startupCost: "투자 원금 필요",
    timeToFirst: "분기~1년",
    difficulty: 3,
  },
  {
    id: "etf-investing",
    name: "ETF 적립식 투자",
    emoji: "📊",
    category: "투자",
    oneline: "매달 적립식으로 ETF 투자",
    description: "S&P500, 나스닥100, 코스피 등 지수 추종 ETF에 매달 일정 금액을 투자하는 방식. 장기 우상향을 기대하는 가장 안정적인 부업 중 하나.",
    incomeRange: "연 5~15% 기대 수익",
    startupCost: "소액 가능",
    timeToFirst: "1년+",
    difficulty: 2,
  },
  {
    id: "crypto",
    name: "코인 투자",
    emoji: "🪙",
    category: "투자",
    oneline: "비트코인·알트코인 투자",
    description: "비트코인, 이더리움 등 암호화폐 투자. 고수익 가능성이 있지만 변동성이 매우 높다. 여유 자금으로만 투자해야 하며 레버리지는 특히 위험하다.",
    incomeRange: "변동성 매우 높음",
    startupCost: "소액 가능",
    timeToFirst: "즉시",
    difficulty: 4,
  },
  {
    id: "p2p-lending",
    name: "P2P 투자 (피플펀드 등)",
    emoji: "🏦",
    category: "투자",
    oneline: "P2P 대출 투자로 이자 수익",
    description: "피플펀드, 어니스트펀드 등 P2P 플랫폼을 통해 대출에 투자하고 이자 수익을 받는다. 연 5~10% 수익을 기대할 수 있지만 원금 손실 위험이 있다.",
    incomeRange: "연 5~10%",
    startupCost: "소액 가능",
    timeToFirst: "1개월",
    difficulty: 2,
  },

  // ─────────────────────────────────────────
  // 배달·서비스
  // ─────────────────────────────────────────
  {
    id: "baemin-rider",
    name: "배달의민족 라이더",
    emoji: "🛵",
    category: "배달·서비스",
    oneline: "배민 라이더로 시간당 수익",
    description: "배달의민족 앱으로 라이더 등록 후 원하는 시간에 배달할 수 있다. 오토바이가 있으면 시간당 수익이 높다. 주말·점심·저녁 시간대가 콜이 많다.",
    incomeRange: "시간당 1.5~2.5만원",
    startupCost: "이동수단 필요",
    timeToFirst: "즉시",
    difficulty: 2,
    officialUrl: "https://rider.baemin.com",
  },
  {
    id: "coupang-flex",
    name: "쿠팡플렉스",
    emoji: "📫",
    category: "배달·서비스",
    oneline: "본인 차량으로 새벽배송 아르바이트",
    description: "본인 차량으로 쿠팡의 새벽배송을 담당하는 프리랜서 배송원. 새벽 2~7시 사이 4~5시간 일하면 5~8만원 수익. 차량이 있으면 즉시 시작 가능.",
    incomeRange: "4~5시간에 5~8만원",
    startupCost: "차량 필요",
    timeToFirst: "즉시",
    difficulty: 2,
    officialUrl: "https://flex.coupang.com",
  },
  {
    id: "kakao-driver",
    name: "카카오T 대리운전",
    emoji: "🚗",
    category: "배달·서비스",
    oneline: "대리운전으로 저녁·주말 수익",
    description: "카카오T, 지정대리운전 앱을 통해 대리운전사로 등록 후 콜을 잡아 수익을 낸다. 금요일·토요일 저녁이 콜이 많고 시간당 수익이 높다.",
    incomeRange: "시간당 1.5~3만원",
    startupCost: "면허·보험 필요",
    timeToFirst: "즉시",
    difficulty: 2,
  },
  {
    id: "kick-charge",
    name: "킥보드 충전 (라임·씽씽)",
    emoji: "🛴",
    category: "배달·서비스",
    oneline: "전동킥보드 수거·충전·재배치로 수익",
    description: "라임, 씽씽, 지쿠 등 공유 킥보드를 집으로 가져가 충전 후 지정 장소에 배치하면 건당 수수료를 받는다. 늦은 밤~새벽에 주로 활동.",
    incomeRange: "건당 1,000~5,000원",
    startupCost: "차량 유리",
    timeToFirst: "즉시",
    difficulty: 1,
  },

  // ─────────────────────────────────────────
  // 디지털콘텐츠
  // ─────────────────────────────────────────
  {
    id: "ebook",
    name: "전자책 출판",
    emoji: "📕",
    category: "디지털콘텐츠",
    oneline: "노하우를 전자책으로 만들어 판매",
    description: "크몽, 탈잉, 카카오페이지, 리디북스, 직접 홈페이지 등 다양한 채널을 통해 PDF 전자책을 판매할 수 있다. 한 번 만들면 계속 수익이 발생하는 패시브 인컴.",
    incomeRange: "월 5~500만원",
    startupCost: "무료",
    timeToFirst: "제작 후",
    difficulty: 2,
    isHot: true,
  },
  {
    id: "notion-template",
    name: "노션 템플릿 판매",
    emoji: "🗂️",
    category: "디지털콘텐츠",
    oneline: "노션 템플릿 제작 후 크몽·Gumroad 판매",
    description: "유용한 노션 템플릿을 만들어 크몽, Gumroad, 노션마켓 등에서 판매한다. 다이어리, 업무관리, 프로젝트 관리 등 다양한 주제로 만들 수 있다.",
    incomeRange: "월 5~200만원",
    startupCost: "무료",
    timeToFirst: "제작 후",
    difficulty: 2,
    isNew: true,
  },
  {
    id: "stock-photo",
    name: "스톡 사진·영상 판매",
    emoji: "📷",
    category: "디지털콘텐츠",
    oneline: "게티이미지·셔터스톡에 사진 판매",
    description: "게티이미지, 셔터스톡, 어도비스톡 등에 사진이나 영상을 올리면 다운로드마다 수수료를 받는다. 사진 품질과 수량이 중요하고 수익이 누적된다.",
    incomeRange: "월 1~50만원",
    startupCost: "카메라 필요",
    timeToFirst: "2~4주",
    difficulty: 3,
  },
  {
    id: "ai-prompt",
    name: "AI 프롬프트 판매",
    emoji: "🤖",
    category: "디지털콘텐츠",
    oneline: "잘 만든 AI 프롬프트를 Promptbase에서 판매",
    description: "ChatGPT, Midjourney, DALL-E 등을 위한 고품질 프롬프트를 Promptbase, 크몽 등에서 판매한다. 새로운 분야이지만 빠르게 성장 중.",
    incomeRange: "건당 1~5달러",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 2,
    isNew: true,
  },
  {
    id: "bgm-music",
    name: "BGM·음악 판매 (AudioJungle)",
    emoji: "🎵",
    category: "디지털콘텐츠",
    oneline: "유튜브용 BGM 제작 후 스톡 사이트 판매",
    description: "AudioJungle, Pond5, 뮤직팟 등에 배경음악을 올리면 다운로드마다 수수료를 받는다. 음악 제작 능력이 있으면 패시브 인컴으로 좋다.",
    incomeRange: "건당 $5~$50",
    startupCost: "장비 비용",
    timeToFirst: "제작 후",
    difficulty: 4,
  },
  {
    id: "figma-template",
    name: "Figma·PPT 템플릿 판매",
    emoji: "🎨",
    category: "디지털콘텐츠",
    oneline: "디자인 템플릿 제작 후 크리에이티브마켓 판매",
    description: "Figma, Canva, 파워포인트 템플릿을 만들어 Creative Market, Gumroad, 크몽 등에서 판매한다. 한 번 만들면 무한 판매 가능한 디지털 상품.",
    incomeRange: "건당 $5~$50",
    startupCost: "무료",
    timeToFirst: "제작 후",
    difficulty: 3,
  },

  // ─────────────────────────────────────────
  // 기타 (특수 온라인 부업)
  // ─────────────────────────────────────────
  {
    id: "esim-palee",
    name: "E심팔이 (eSIM 재판매)",
    emoji: "📡",
    category: "기타",
    oneline: "eSIM 리셀러로 해외여행자에게 판매",
    description: "해외 여행용 eSIM을 도매로 구매해 SNS나 블로그에서 소매로 재판매하는 비즈니스. 여행 수요가 있는 시즌에 수익이 높고, 고객 관리가 핵심.",
    incomeRange: "월 10~200만원",
    startupCost: "소액",
    timeToFirst: "1~2주",
    difficulty: 2,
    isHot: true,
    isNew: true,
  },
  {
    id: "reelfix",
    name: "릴픽스",
    emoji: "🎬",
    category: "기타",
    oneline: "릴스·쇼츠 영상 편집 대행 플랫폼",
    description: "릴픽스는 영상 편집자와 콘텐츠 제작자를 연결하는 플랫폼. 영상 편집 능력이 있으면 숏폼 영상 편집을 맡아 수익을 낼 수 있다.",
    incomeRange: "건당 2~10만원",
    startupCost: "무료 (편집 툴 필요)",
    timeToFirst: "즉시",
    difficulty: 3,
    isNew: true,
    isHot: true,
  },
  {
    id: "chatgpt-service",
    name: "AI 자동화 서비스 판매",
    emoji: "🤖",
    category: "기타",
    oneline: "ChatGPT·AI 활용 업무 자동화 서비스",
    description: "ChatGPT, Claude, Zapier 등을 활용해 블로그 자동화, 보고서 생성, 데이터 분석 자동화 등의 서비스를 크몽이나 직접 판매한다. 기술 장벽이 낮아지고 있는 분야.",
    incomeRange: "건당 5~100만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 3,
    isNew: true,
    isHot: true,
  },
  {
    id: "translation",
    name: "번역 프리랜서 (플리토 등)",
    emoji: "🌐",
    category: "기타",
    oneline: "영어·일어 등 번역으로 수익",
    description: "플리토, 원스톱번역, 크몽 등에서 번역 서비스를 제공한다. 전문 분야(법률, 의학, IT 등) 번역은 단가가 높다. 영어 외 일본어·중국어도 수요가 많다.",
    incomeRange: "월 10~100만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 3,
  },
  {
    id: "virtual-assistant",
    name: "가상 비서 (VA) 서비스",
    emoji: "🗓️",
    category: "기타",
    oneline: "원격으로 업무 지원 서비스 제공",
    description: "일정 관리, 이메일 응대, 자료 조사, SNS 관리 등의 업무를 원격으로 지원하는 가상 비서 서비스. 해외 클라이언트를 대상으로 하면 수익이 높다.",
    incomeRange: "시간당 1~5만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 2,
  },
  {
    id: "nft",
    name: "NFT 제작·판매",
    emoji: "🎨",
    category: "기타",
    oneline: "디지털 아트를 NFT로 만들어 판매",
    description: "OpenSea, 클립 드롭스 등에서 디지털 아트나 콘텐츠를 NFT로 발행해 판매한다. 시장이 침체되어 있지만 독창적인 작품은 여전히 거래된다.",
    incomeRange: "변동성 매우 높음",
    startupCost: "가스비 필요",
    timeToFirst: "1~4주",
    difficulty: 4,
  },
  {
    id: "game-boosting",
    name: "게임 대리육성·코칭",
    emoji: "🎮",
    category: "기타",
    oneline: "고티어 실력으로 대리육성 수익",
    description: "롤, 발로란트 등 게임의 대리육성 또는 코칭 서비스를 제공한다. 플래티넘 이상 티어면 가능하고, 코칭 플랫폼(게임코치온라인 등)을 활용하면 합법적으로 가능.",
    incomeRange: "건당 1~5만원",
    startupCost: "무료",
    timeToFirst: "즉시",
    difficulty: 3,
  },
];

export const HUSTLE_MAP: Record<string, SideHustle> = Object.fromEntries(
  ALL_HUSTLES.map((h) => [h.id, h])
);

export function getHustlesByCategory(category: HustleCategory): SideHustle[] {
  return ALL_HUSTLES.filter((h) => h.category === category);
}

export function searchHustles(query: string): SideHustle[] {
  const q = query.toLowerCase();
  if (!q) return ALL_HUSTLES;
  return ALL_HUSTLES.filter(
    (h) =>
      h.name.toLowerCase().includes(q) ||
      h.oneline.toLowerCase().includes(q) ||
      h.category.toLowerCase().includes(q)
  );
}
