import type { Review } from "./types";

export const MOCK_REVIEWS: Review[] = [
  {
    id: "1",
    created_at: "2026-04-20T10:00:00Z",
    nickname: "블로그수익6개월",
    hustle_id: "naver-blog",
    hustle_name: "네이버 블로그 (애드포스트)",
    income_range: "10_to_30",
    weekly_hours: 5,
    difficulty: 2,
    satisfaction: 4,
    title: "네이버 블로그 애드포스트 6개월 - 생각보다 현실적",
    content: "처음엔 한 달에 100만원 벌 수 있다는 글 보고 시작했는데 현실은 달랐어요. 6개월 동안 꾸준히 하니 월 20만원 정도 나오네요. 키워드 선정이 제일 중요한 것 같아요.",
    pros: "시간 자유롭고 한 번 쓴 글이 계속 수익 낸다",
    cons: "수익 나기까지 최소 6개월. 꾸준함이 필수",
    recommend: true,
    likes: 47,
  },
  {
    id: "2",
    created_at: "2026-04-19T14:30:00Z",
    nickname: "퇴근후라이더",
    hustle_id: "baemin-rider",
    hustle_name: "배달의민족 라이더",
    income_range: "30_to_50",
    weekly_hours: 10,
    difficulty: 2,
    satisfaction: 3,
    title: "배민 라이더 6개월차 - 몸은 힘들지만 즉시 수익",
    content: "퇴근 후 주말 포함 주 10시간 정도 뛰면 월 40만원 선. 날씨 나쁜 날엔 수당 더 높아서 오히려 많이 벌기도 해요. 체력이 관건이고 사고 위험은 감수해야 합니다.",
    pros: "즉시 수익, 자유로운 시간 선택, 운동효과",
    cons: "날씨 영향, 사고 위험, 체력 소모 큼",
    recommend: true,
    likes: 38,
  },
  {
    id: "3",
    created_at: "2026-04-18T09:15:00Z",
    nickname: "개발자N잡",
    hustle_id: "kmong",
    hustle_name: "크몽",
    income_range: "over_100",
    weekly_hours: 15,
    difficulty: 4,
    satisfaction: 5,
    title: "크몽 개발 외주 1년 - 월 150만원 추가수익 달성",
    content: "개발자라 크몽에서 외주 받습니다. 처음 6개월은 포트폴리오 쌓느라 낮은 단가로 했지만, 이제는 프로젝트 골라서 받아요. 후기 쌓이고 나서 단가 두 배 올렸어요.",
    pros: "높은 시급, 기술 성장, 포트폴리오 강화",
    cons: "마감 압박, 클라이언트 스트레스, 초기 단가 낮음",
    recommend: true,
    likes: 92,
  },
  {
    id: "4",
    created_at: "2026-04-17T20:00:00Z",
    nickname: "스마트스토어주부",
    hustle_id: "smart-store",
    hustle_name: "스마트스토어",
    income_range: "30_to_50",
    weekly_hours: 20,
    difficulty: 3,
    satisfaction: 4,
    title: "스마트스토어 8개월차 - 매출은 나오는데 순이익은...",
    content: "매출은 월 300만원인데 광고비, 택배비, 플랫폼 수수료 빼면 순이익 35만원 정도예요. 생각보다 마진 관리가 어렵습니다. 위탁판매로 시작해서 직매입으로 전환 중.",
    pros: "재택 가능, 내 사업 운영 경험, 성장 가능성",
    cons: "초기 재고 부담, CS 스트레스, 광고비 압박",
    recommend: true,
    likes: 61,
  },
  {
    id: "5",
    created_at: "2026-04-16T11:00:00Z",
    nickname: "유튜브포기자",
    hustle_id: "youtube",
    hustle_name: "유튜브 채널 운영",
    income_range: "under_10",
    weekly_hours: 12,
    difficulty: 5,
    satisfaction: 2,
    title: "유튜브 1년 했는데 구독자 300명... 솔직한 실패 후기",
    content: "편집, 썸네일, 대본 다 혼자 하면서 주 12시간 투자했는데 1년에 구독자 300명. 수익은 거의 0. 콘텐츠 기획력이 없으면 정말 어렵습니다.",
    pros: "콘텐츠 제작 스킬 향상",
    cons: "성과 불확실, 시간 대비 수익 최악, 정신적 소모 큼",
    recommend: false,
    likes: 103,
  },
  {
    id: "6",
    created_at: "2026-04-15T16:45:00Z",
    nickname: "강사투잡",
    hustle_id: "class101",
    hustle_name: "클래스101",
    income_range: "50_to_100",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 5,
    title: "클래스101 포토샵 강의로 월 70만원 - 자동수익의 꿈",
    content: "본업이 디자이너라 포토샵 강의 올렸어요. 처음 강의 제작에 2달 걸렸지만, 이후엔 거의 자동으로 수익 납니다. 플랫폼 수수료가 높아서 자체 채널 구축도 고민 중.",
    pros: "제작 후 자동수익, 전문성 인정받는 느낌, 시간 자유",
    cons: "초기 제작 시간 많이 필요, 플랫폼 수수료 높음",
    recommend: true,
    likes: 78,
  },
  {
    id: "7",
    created_at: "2026-04-14T08:30:00Z",
    nickname: "쿠팡파트너스3년",
    hustle_id: "coupang-partners",
    hustle_name: "쿠팡파트너스",
    income_range: "30_to_50",
    weekly_hours: 3,
    difficulty: 1,
    satisfaction: 5,
    title: "쿠팡파트너스 3년차 - 블로그 글 200개로 월 40만원 패시브",
    content: "블로그에 상품 리뷰 200개 정도 써두니 지금은 주 2~3시간만 신경 써도 월 40만원이 들어와요. 수익률이 제일 좋은 카테고리는 가전제품이에요.",
    pros: "완전 패시브 인컴 가능, 시작 무료",
    cons: "트래픽 없으면 수익 0, 쿠팡 정책 변경 리스크",
    recommend: true,
    likes: 134,
  },
  {
    id: "8",
    created_at: "2026-04-13T18:00:00Z",
    nickname: "코인손절경험자",
    hustle_id: "crypto",
    hustle_name: "코인 투자",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 4,
    satisfaction: 1,
    title: "코인으로 500만원 날린 후기 - 제발 따라하지 마세요",
    content: "유튜브 코인 유튜버 따라했다가 500만원 손실. 지금도 물려있어요. 레버리지 쓰면 진짜 한 방에 갑니다. 여유 자금으로만 하세요.",
    pros: "없음",
    cons: "손실 위험, 레버리지 위험, 수면 방해",
    recommend: false,
    likes: 156,
  },
  {
    id: "9",
    created_at: "2026-04-12T10:30:00Z",
    nickname: "KREAM리셀러",
    hustle_id: "kream",
    hustle_name: "KREAM 스니커즈·의류 리셀",
    income_range: "30_to_50",
    weekly_hours: 5,
    difficulty: 3,
    satisfaction: 4,
    title: "KREAM 리셀 6개월 - 신발 지식 없으면 시작하지 마세요",
    content: "나이키, 뉴발란스 한정판 발매 때마다 응모해서 당첨되면 팔아요. 월 평균 30~40만원 수익. 근데 발매 응모가 복권이라 달이 다 달라요. 시세 파악이 진짜 중요합니다.",
    pros: "높은 건당 수익, 취미와 결합 가능",
    cons: "재고 손실 위험, 응모 불확실성, 시세 하락 리스크",
    recommend: true,
    likes: 67,
  },
  {
    id: "10",
    created_at: "2026-04-11T15:00:00Z",
    nickname: "유튜브성공기",
    hustle_id: "youtube",
    hustle_name: "유튜브 채널 운영",
    income_range: "50_to_100",
    weekly_hours: 15,
    difficulty: 5,
    satisfaction: 5,
    title: "먹방 유튜브 2년 만에 구독자 5만명, 월 60만원",
    content: "처음 1년은 구독자 2천명이었어요. 포기 안 하고 꾸준히 올리다 보니 알고리즘 타면서 성장했습니다. 협찬도 들어와서 광고 수익 이상으로 벌기도 해요.",
    pros: "성장 후 눈덩이 효과, 협찬 수입",
    cons: "성장 전까지 긴 무수익 기간",
    recommend: true,
    likes: 134,
  },
  {
    id: "11",
    created_at: "2026-04-10T09:00:00Z",
    nickname: "에이블리판매자",
    hustle_id: "ably-seller",
    hustle_name: "에이블리 셀러",
    income_range: "30_to_50",
    weekly_hours: 10,
    difficulty: 3,
    satisfaction: 4,
    title: "에이블리 의류 판매 4개월 - 스마트스토어보다 낫네요",
    content: "스마트스토어 했다가 에이블리로 옮겼어요. 여성 패션에 특화돼서 타깃 고객이 명확하고 리뷰 관리가 편해요. 월 순이익 35~40만원 정도 나와요.",
    pros: "타깃 명확, 운영 편리, 꾸준한 매출",
    cons: "패션에만 특화, 수수료 있음",
    recommend: true,
    likes: 42,
  },
  {
    id: "12",
    created_at: "2026-04-09T14:00:00Z",
    nickname: "쿠팡플렉스새벽",
    hustle_id: "coupang-flex",
    hustle_name: "쿠팡플렉스",
    income_range: "30_to_50",
    weekly_hours: 20,
    difficulty: 2,
    satisfaction: 3,
    title: "쿠팡플렉스 새벽배송 3개월 후기 - 새벽 4시의 현실",
    content: "새벽 2시에 집합해서 7시까지 하면 6만원. 주 4일 하면 월 96만원인데 너무 힘들어서 주 3일로 줄였어요. 육체적으로 정말 힘들지만 수입은 확실합니다.",
    pros: "확실한 수입, 내 차 활용",
    cons: "새벽 근무 체력 소모, 아파트 엘리베이터 대기 스트레스",
    recommend: true,
    likes: 55,
  },
  {
    id: "13",
    created_at: "2026-04-08T11:30:00Z",
    nickname: "전자책작가",
    hustle_id: "ebook",
    hustle_name: "전자책 출판",
    income_range: "10_to_30",
    weekly_hours: 2,
    difficulty: 2,
    satisfaction: 5,
    title: "크몽 전자책 3개 올려서 월 20만원 패시브",
    content: "직장생활 꿀팁, 엑셀 활용법, 취업 면접 전략 전자책 3개 올려뒀어요. 이제는 거의 손 안 대도 월 20만원씩 들어와요. 처음 쓰는 게 제일 힘들었지만 지금은 만족.",
    pros: "완전 패시브, 한 번 제작으로 지속 수익",
    cons: "처음 제작에 시간 투자 필요, 콘텐츠 품질이 수익 좌우",
    recommend: true,
    likes: 89,
  },
  {
    id: "14",
    created_at: "2026-04-07T16:00:00Z",
    nickname: "E심팔이경험자",
    hustle_id: "esim-palee",
    hustle_name: "E심팔이 (eSIM 재판매)",
    income_range: "10_to_30",
    weekly_hours: 5,
    difficulty: 2,
    satisfaction: 4,
    title: "E심팔이 시작 2개월 - 여행 시즌에 진짜 터짐",
    content: "인스타랑 네이버 블로그로 홍보하고 있어요. 평소엔 월 15만원 정도인데 황금연휴, 여름휴가 시즌엔 월 50만원 이상 나왔어요. 초기 셋업이 좀 복잡하지만 시스템 구축되면 자동화 가능.",
    pros: "여행 시즌 고수익, 재고 부담 적음",
    cons: "평소엔 수익 들쭉날쭉, 고객 CS 필요",
    recommend: true,
    likes: 78,
  },
  {
    id: "15",
    created_at: "2026-04-06T10:00:00Z",
    nickname: "릴픽스편집자",
    hustle_id: "reelfix",
    hustle_name: "릴픽스",
    income_range: "10_to_30",
    weekly_hours: 10,
    difficulty: 3,
    satisfaction: 4,
    title: "릴픽스로 쇼츠 편집 월 20만원 - 영상 편집 부업의 현실",
    content: "프리미어프로 다룰 줄 알면 바로 시작 가능해요. 건당 2~5만원인데 빠른 분들은 하루 2~3개도 한다고 하던데 저는 아직 하루 1개 수준이에요. 스타일 익히면 속도 빨라질 것 같아요.",
    pros: "재택 가능, 영상 스킬 향상, 즉시 시작",
    cons: "단가 높지 않음, 클라이언트 피드백 수정 번거로움",
    recommend: true,
    likes: 45,
  },
  {
    id: "16",
    created_at: "2026-04-05T13:00:00Z",
    nickname: "데이터라벨러",
    hustle_id: "data-labeling",
    hustle_name: "데이터 라벨링",
    income_range: "under_10",
    weekly_hours: 8,
    difficulty: 1,
    satisfaction: 2,
    title: "데이터 라벨링 3개월 - 누구나 할 수 있는 대신 수익도 낮음",
    content: "크라우드웍스에서 이미지 분류 작업 했어요. 월 8~10만원. 아무 기술 없어도 할 수 있는 게 장점이지만 시간당 수익이 너무 낮아요. 용돈벌이 정도로 생각하세요.",
    pros: "누구나 가능, 자투리 시간 활용",
    cons: "시간 대비 수익 매우 낮음",
    recommend: false,
    likes: 33,
  },
  {
    id: "17",
    created_at: "2026-04-04T09:30:00Z",
    nickname: "노션템플릿판매",
    hustle_id: "notion-template",
    hustle_name: "노션 템플릿 판매",
    income_range: "10_to_30",
    weekly_hours: 2,
    difficulty: 2,
    satisfaction: 5,
    title: "노션 템플릿 5개로 월 15만원 - 완전 새로운 디지털 상품",
    content: "업무일지, 독서 기록, 여행 계획, 스터디 플래너 등 5개 템플릿 만들어서 크몽이랑 Gumroad에 올려뒀어요. 이제는 거의 손 안 대도 돈이 들어와요. 생각보다 수요가 많아요.",
    pros: "완전 패시브, 제작비 0원, 무한 복제 판매",
    cons: "수요 예측 어려움, 비슷한 무료 템플릿과 경쟁",
    recommend: true,
    likes: 67,
  },
  {
    id: "18",
    created_at: "2026-04-03T17:00:00Z",
    nickname: "AI자동화프리랜서",
    hustle_id: "chatgpt-service",
    hustle_name: "AI 자동화 서비스 판매",
    income_range: "50_to_100",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 5,
    title: "ChatGPT 활용 블로그 자동화 서비스로 월 80만원",
    content: "소상공인들한테 ChatGPT로 블로그 글 자동 생성 시스템 만들어드려요. 초기 셋업비 50만원 + 월 유지비 10만원 모델로 운영 중. 지금 클라이언트 7명이에요.",
    pros: "높은 단가, 지속적인 수익, 수요 급증",
    cons: "초기 클라이언트 모집 어려움, AI 기술 빠르게 변함",
    recommend: true,
    likes: 112,
  },
  {
    id: "19",
    created_at: "2026-04-02T10:00:00Z",
    nickname: "틱토커도전중",
    hustle_id: "tiktok",
    hustle_name: "틱톡 크리에이터",
    income_range: "under_10",
    weekly_hours: 6,
    difficulty: 3,
    satisfaction: 3,
    title: "틱톡 팔로워 2만명인데 수익화 방법을 모르겠어요",
    content: "팔로워 2만명 모았는데 한국에서 틱톡 수익화가 잘 안 된다는 걸 뒤늦게 알았어요. 협찬 연락은 가끔 오는데 단가가 낮아요. 인스타 연동으로 수익 채널 다각화 중입니다.",
    pros: "빠른 성장 가능, 영상 스킬 향상",
    cons: "한국 수익화 체계 미흡, 협찬 단가 낮음",
    recommend: true,
    likes: 41,
  },
  {
    id: "20",
    created_at: "2026-04-01T14:00:00Z",
    nickname: "위시켓개발자",
    hustle_id: "wishket",
    hustle_name: "위시켓",
    income_range: "over_100",
    weekly_hours: 20,
    difficulty: 4,
    satisfaction: 5,
    title: "위시켓으로 React 프로젝트 하나에 300만원",
    content: "풀타임 직장 다니면서 위시켓 단기 프로젝트 하나 받아서 2달에 300만원 받았어요. 계약서 꼼꼼히 쓰는 게 진짜 중요해요. 요구사항 변경이 제일 스트레스지만 단가 높아서 만족.",
    pros: "높은 단가, 기술 성장, 포트폴리오",
    cons: "일정 관리 어려움, 요구사항 변경, 야근 가능성",
    recommend: true,
    likes: 119,
  },
  {
    id: "21",
    created_at: "2026-03-31T09:00:00Z",
    nickname: "번개장터리셀러",
    hustle_id: "bunjang-resell",
    hustle_name: "번개장터 리셀",
    income_range: "10_to_30",
    weekly_hours: 6,
    difficulty: 2,
    satisfaction: 4,
    title: "번개장터 중고 리셀 - 포켓몬 카드로 월 25만원",
    content: "편의점에서 포켓몬 카드 신상 풀어줄 때마다 줄 서서 사서 희귀 카드 분리해 팔아요. 리스크 있지만 희귀도 높은 카드 나오면 한 장에 10만원 이상도 받아요.",
    pros: "즉시 현금화, 취미와 결합, 높은 건당 수익",
    cons: "가격 변동 심함, 재고 손실 가능성",
    recommend: true,
    likes: 53,
  },
  {
    id: "22",
    created_at: "2026-03-30T15:00:00Z",
    nickname: "ETF적립러",
    hustle_id: "etf-investing",
    hustle_name: "ETF 적립식 투자",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 2,
    satisfaction: 4,
    title: "직장인 적립식 ETF 2년 - 수익률 +18%, 스트레스 없는 투자",
    content: "매달 30만원씩 S&P500 ETF 적립식 투자 중입니다. 2년 수익률 +18%. 빠른 부업은 아니지만 가장 스트레스 없는 방법이에요. 단타나 코인은 포기하고 장기로 갑니다.",
    pros: "스트레스 없음, 자산 형성, 복리 효과",
    cons: "단기 수익 없음, 인내심 필요, 원금 손실 가능",
    recommend: true,
    likes: 74,
  },
  {
    id: "23",
    created_at: "2026-03-29T11:00:00Z",
    nickname: "온라인과외선생",
    hustle_id: "online-tutoring",
    hustle_name: "온라인 과외 (과외앱)",
    income_range: "50_to_100",
    weekly_hours: 6,
    difficulty: 2,
    satisfaction: 5,
    title: "수학 온라인 과외 - 시간당 4만원, 월 80만원",
    content: "아이캔이랑 과외닷컴 동시에 올려서 학생 4명 받고 있어요. 비대면이라 이동 시간 없고 편해요. 처음엔 단가 협상이 어려웠는데 후기 쌓이니까 올릴 수 있었어요.",
    pros: "높은 시간당 단가, 이동 없음, 학생 성장 보람",
    cons: "학부모 연락 부담, 성적 압박",
    recommend: true,
    likes: 68,
  },
  {
    id: "24",
    created_at: "2026-03-28T08:30:00Z",
    nickname: "tistory애드센스",
    hustle_id: "tistory",
    hustle_name: "티스토리 블로그 (구글 애드센스)",
    income_range: "30_to_50",
    weekly_hours: 6,
    difficulty: 3,
    satisfaction: 4,
    title: "티스토리 애드센스 2년 - 월 40만원 달성한 방법",
    content: "구글 SEO 집중해서 영어권 검색 유입도 노렸어요. 단가가 네이버보다 훨씬 높아요. 애드센스 승인받는 게 제일 어려웠고, 이후엔 꾸준히 글 쓰는 게 전부예요.",
    pros: "높은 광고 단가, 구글 트래픽 확보 가능",
    cons: "애드센스 승인 어려움, SEO 공부 필요",
    recommend: true,
    likes: 82,
  },
  {
    id: "25",
    created_at: "2026-03-27T14:30:00Z",
    nickname: "패널나우설문러",
    hustle_id: "panel-now",
    hustle_name: "패널나우·설문조사",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 1,
    satisfaction: 3,
    title: "설문조사 앱 6개 동시에 - 월 5만원의 현실",
    content: "패널나우, 엠브레인, 서베이링크, 오픈서베이 등 6개 동시에 해도 월 5만원 정도예요. 시간 낭비라고 생각할 수도 있지만 이동 중에 하면 나쁘진 않아요.",
    pros: "언제 어디서나 가능, 기술 불필요",
    cons: "수익 매우 낮음, 자투리 시간 이상 투자 불필요",
    recommend: false,
    likes: 28,
  },
  {
    id: "26",
    created_at: "2026-03-26T10:00:00Z",
    nickname: "유데미강사",
    hustle_id: "udemy",
    hustle_name: "유데미 (Udemy) 강의 등록",
    income_range: "10_to_30",
    weekly_hours: 2,
    difficulty: 3,
    satisfaction: 4,
    title: "유데미 파이썬 강의 올리고 달러 수익 - 2년째 자동수익",
    content: "2년 전에 파이썬 기초 강의 올렸는데 지금도 월 20달러~30달러 들어와요. 할인할 때 많이 팔려서 수익이 불규칙하지만 완전 자동이에요. 영어 강의라면 수익 훨씬 높아요.",
    pros: "글로벌 수요, 완전 자동 수익",
    cons: "할인 정책으로 단가 낮음, 리뷰 관리 중요",
    recommend: true,
    likes: 44,
  },
  {
    id: "27",
    created_at: "2026-03-25T16:00:00Z",
    nickname: "아마존FBA도전",
    hustle_id: "amazon-fba",
    hustle_name: "아마존 FBA",
    income_range: "over_100",
    weekly_hours: 15,
    difficulty: 5,
    satisfaction: 4,
    title: "아마존 FBA 1년 - 초기 500만원 투자 후 현재 월 200만원",
    content: "K-뷰티 제품으로 시작해서 1년째예요. 초기 재고, FBA 수수료, 광고비로 500만원 정도 썼고 이제는 월 200만원 수익 나와요. 진입장벽 높지만 스케일업 가능성 최고.",
    pros: "달러 수익, 자동화 가능, 글로벌 시장",
    cons: "초기 투자 크고, 학습 곡선 높음",
    recommend: true,
    likes: 88,
  },
  {
    id: "28",
    created_at: "2026-03-24T09:00:00Z",
    nickname: "숨고튜터",
    hustle_id: "soomgo",
    hustle_name: "숨고",
    income_range: "30_to_50",
    weekly_hours: 8,
    difficulty: 2,
    satisfaction: 4,
    title: "숨고 피트니스 PT 코치 - 월 40만원 추가 수입",
    content: "본업 PT 강사인데 숨고로 온라인 PT도 시작했어요. 오프라인보다 단가는 낮지만 이동 시간 없고 스케줄 관리가 편해요. 후기 10개 넘으니까 문의가 꾸준히 들어와요.",
    pros: "이동 없음, 꾸준한 수요, 전문성 활용",
    cons: "단가 협상, 노쇼 가능성",
    recommend: true,
    likes: 37,
  },
  {
    id: "29",
    created_at: "2026-03-23T13:00:00Z",
    nickname: "인스타쇼핑몰운영",
    hustle_id: "instagram-shop",
    hustle_name: "인스타그램 쇼핑몰",
    income_range: "10_to_30",
    weekly_hours: 12,
    difficulty: 3,
    satisfaction: 3,
    title: "인스타 의류 쇼핑몰 1년 - 팔로워 6천명에 월 20만원",
    content: "사진 찍고 편집하고 DM 답장하고... 생각보다 손이 많이 가요. 팔로워 6천명에 월 순이익 20만원. 시간 대비 효율이 낮지만 브랜드 만드는 재미가 있어서 계속하는 중.",
    pros: "낮은 플랫폼 수수료, 브랜드 구축",
    cons: "콘텐츠 제작 부담, 24시간 DM 관리",
    recommend: true,
    likes: 29,
  },
  {
    id: "30",
    created_at: "2026-03-22T11:00:00Z",
    nickname: "스톡사진작가",
    hustle_id: "stock-photo",
    hustle_name: "스톡 사진·영상 판매",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 3,
    satisfaction: 3,
    title: "셔터스톡에 사진 500장 올린 결과 - 월 3만원의 현실",
    content: "1년 동안 500장 올렸는데 월 3만원 정도 나와요. 생각보다 경쟁이 심하고 AI 생성 이미지들이 쏟아지면서 단가가 많이 내려갔어요. 사진 좋아하면 할 수 있지만 기대치 낮추세요.",
    pros: "취미 수익화, 완전 패시브",
    cons: "AI 경쟁으로 단가 하락, 수익 낮음",
    recommend: false,
    likes: 45,
  },
];
