import { config } from "dotenv";
config({ path: ".env.local", override: true });

import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const D = "※ 이 후기는 인터넷 공개 정보를 바탕으로 작성되었습니다";

interface ReviewInsert {
  nickname: string;
  hustle_id: string;
  hustle_name: string;
  income_range: string;
  weekly_hours: number;
  difficulty: number;
  satisfaction: number;
  title: string;
  content: string;
  pros: string;
  cons: string;
  recommend: boolean;
}

const reviews: ReviewInsert[] = [
  // ── 유튜브 채널 운영 ──
  {
    nickname: "영상쟁이박씨",
    hustle_id: "youtube",
    hustle_name: "유튜브 채널 운영",
    income_range: "50_to_100",
    weekly_hours: 15,
    difficulty: 5,
    satisfaction: 4,
    title: "구독자 1만 모으는 데 8개월, 그래도 계속하는 이유",
    content: `요리 채널 운영한 지 1년이 넘었어요. 처음 6개월은 수익이 거의 없었고 구독자도 안 늘었는데, 꾸준히 올리다 보니 알고리즘이 한 번 터지면서 구독자가 빠르게 늘었습니다. 지금은 월 60~80만원 정도 광고 수익이 나오고, 협찬 문의도 가끔 들어와요. 영상 하나 찍고 편집하는 데 평균 5~6시간은 잡아야 해서 본업이 바쁠 때는 정말 힘들었습니다. ${D}`,
    pros: "한 번 성장하면 자동 수익, 브랜딩 효과",
    cons: "성장까지 최소 6개월~1년, 편집 시간 많이 소요",
    recommend: true,
  },
  {
    nickname: "유튜브도전중",
    hustle_id: "youtube",
    hustle_name: "유튜브 채널 운영",
    income_range: "under_10",
    weekly_hours: 10,
    difficulty: 5,
    satisfaction: 2,
    title: "6개월째 수익 0원, 현실은 냉혹했다",
    content: `브이로그 채널 6개월 운영 중인데 구독자 380명에 수익은 거의 없어요. 유튜브 파트너 프로그램 가입 기준(구독자 1000명, 조회수 4000시간)을 아직 못 채웠습니다. 영상 퀄리티를 높이려고 카메라도 샀는데 투자비도 못 건지고 있어요. 롱런하는 마인드가 없으면 빨리 포기하게 됩니다. ${D}`,
    pros: "창작 활동 자체가 즐거움",
    cons: "수익화까지 매우 오래 걸림, 장비 투자비 부담",
    recommend: false,
  },

  // ── 유튜브 쇼츠 ──
  {
    nickname: "쇼츠부자되자",
    hustle_id: "youtube-shorts",
    hustle_name: "유튜브 쇼츠",
    income_range: "10_to_30",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 3,
    title: "쇼츠 조회수 100만 나왔는데 수익은 고작 3만원",
    content: `밈 편집 쇼츠 채널 운영 중인데 100만 조회수 영상이 나왔을 때 수익이 3만원밖에 안 돼서 충격받았어요. 쇼츠 RPM(1000뷰당 수익)이 롱폼보다 훨씬 낮습니다. 그나마 쇼츠로 구독자를 빠르게 모아서 롱폼으로 유도하는 전략이 맞는 것 같아요. 채널 성장 도구로는 좋은데 단독 수익화는 기대 이하입니다. ${D}`,
    pros: "빠른 채널 성장, 제작 시간 짧음",
    cons: "광고 단가 매우 낮음, 단독 수익화 어려움",
    recommend: true,
  },
  {
    nickname: "숏폼중독자",
    hustle_id: "youtube-shorts",
    hustle_name: "유튜브 쇼츠",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 2,
    satisfaction: 3,
    title: "매일 1개씩 올렸더니 3개월 만에 구독자 5천",
    content: `지식공유 쇼츠를 매일 업로드했더니 3개월에 구독자 5천 명 모였어요. 근데 수익은 월 5만원도 안 됩니다. 쇼츠 수익화보다는 채널 키워서 롱폼이나 강의 판매로 연결하는 게 현실적인 것 같아요. 스마트폰으로 편집하면 1시간 안에 하나 만들 수 있어서 진입장벽은 낮아요. ${D}`,
    pros: "스마트폰만으로 제작 가능, 빠른 성장",
    cons: "수익 자체는 매우 적음",
    recommend: true,
  },

  // ── 틱톡 크리에이터 ──
  {
    nickname: "틱톡댄서준호",
    hustle_id: "tiktok",
    hustle_name: "틱톡 크리에이터",
    income_range: "10_to_30",
    weekly_hours: 7,
    difficulty: 3,
    satisfaction: 4,
    title: "팔로워 3만에 협찬 월 20만원, 생각보다 쏠쏠해요",
    content: `일상 브이로그와 댄스 영상 올리다 보니 팔로워 3만 명 됐어요. 틱톡 자체 수익화(Creator Fund)는 정말 적고 건당 5~10만원짜리 소규모 협찬이 수입의 대부분입니다. 팔로워 늘어나는 속도가 인스타보다 빠른 게 장점이에요. 다만 틱톡이 한국 알고리즘보다 해외에 더 최적화된 느낌이라 영어 콘텐츠가 유리합니다. ${D}`,
    pros: "알고리즘 덕분에 빠른 성장, 협찬 연결 쉬움",
    cons: "자체 수익 매우 낮음, 앱 규제 불확실성",
    recommend: true,
  },
  {
    nickname: "틱톡포기함",
    hustle_id: "tiktok",
    hustle_name: "틱톡 크리에이터",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 3,
    satisfaction: 2,
    title: "팔로워 1만인데 수익화 방법을 모르겠다",
    content: `3개월 열심히 해서 팔로워 1만 찍었는데 실질 수익이 없어요. 틱톡 Creator Fund는 조건도 까다롭고 돈도 안 됩니다. 협찬은 팔로워 최소 5만은 돼야 연락이 오는 것 같아요. 인스타로 팔로워를 옮기는 브릿지 역할로 쓰는 게 낫겠다고 생각 중입니다. 시간 대비 수익이 너무 낮아요. ${D}`,
    pros: "빠른 팔로워 증가",
    cons: "수익화 경로 불명확, 국내 플랫폼 지원 약함",
    recommend: false,
  },

  // ── 인스타그램 협찬·광고 ──
  {
    nickname: "인스타마켓터",
    hustle_id: "instagram-sponsor",
    hustle_name: "인스타그램 협찬·광고",
    income_range: "50_to_100",
    weekly_hours: 10,
    difficulty: 4,
    satisfaction: 4,
    title: "팔로워 2만으로 월 70만원 협찬 받는 방법",
    content: `뷰티 계정으로 팔로워 2만 명 운영 중이에요. 팔로워 수보다 참여율(좋아요+댓글 비율)이 중요해서 소규모 계정도 협찬 받을 수 있어요. 건당 5~15만원짜리 제품 협찬이 월 4~6건 들어옵니다. 처음 팔로워 1만 모으기가 제일 힘들었고, 이후엔 자연스럽게 문의가 들어와요. 릴스 조회수가 높으면 더 유리합니다. ${D}`,
    pros: "참여율 높으면 소규모 계정도 협찬 가능",
    cons: "팔로워 1만 모으기까지 매우 오래 걸림",
    recommend: true,
  },
  {
    nickname: "인스타일상계정",
    hustle_id: "instagram-sponsor",
    hustle_name: "인스타그램 협찬·광고",
    income_range: "under_10",
    weekly_hours: 6,
    difficulty: 4,
    satisfaction: 2,
    title: "팔로워 5천인데 협찬은 언제 오나요",
    content: `일상 사진 꾸준히 올린 지 1년인데 팔로워 5천 명으로 성장이 정체됐어요. 협찬 문의는 가끔 오는데 제품 제공만 하고 현금은 없는 경우가 대부분입니다. 팔로워 1만 이상은 돼야 현금 협찬이 시작된다고 봐야 해요. 참여율을 높이려고 스토리, 릴스 다 하고 있는데 정말 지쳐요. ${D}`,
    pros: "본인 취향 콘텐츠 운영 가능",
    cons: "팔로워 성장 더디면 수익화까지 너무 오래 걸림",
    recommend: false,
  },

  // ── 네이버 인플루언서 ──
  {
    nickname: "네이버블로거나야",
    hustle_id: "naver-influencer",
    hustle_name: "네이버 인플루언서",
    income_range: "30_to_50",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 4,
    title: "인플루언서 선정 후 월 수익이 3배 뛰었어요",
    content: `맛집 리뷰로 네이버 인플루언서 선정된 지 6개월 됐어요. 선정 전에는 애드포스트 수익이 월 5만원 수준이었는데 선정 후 키워드 챌린지, 팬심 등 추가 수익원이 생기면서 월 35~45만원까지 올랐습니다. 체험단 신청도 훨씬 잘 됩니다. 선정 기준이 까다롭긴 한데 일단 되면 확실히 달라져요. ${D}`,
    pros: "선정 후 수익 급증, 체험단 우대",
    cons: "인플루언서 선정 기준이 불명확하고 까다로움",
    recommend: true,
  },
  {
    nickname: "인플루언서지망생",
    hustle_id: "naver-influencer",
    hustle_name: "네이버 인플루언서",
    income_range: "10_to_30",
    weekly_hours: 6,
    difficulty: 3,
    satisfaction: 3,
    title: "인플루언서 선정까지 1년 넘게 걸렸어요",
    content: `운동 분야로 인플루언서 신청해서 두 번 떨어지고 세 번째에 선정됐어요. 1년 3개월 걸렸습니다. 현재 월 15~25만원 수익인데 글 쓰는 시간 생각하면 시급이 높지 않아요. 그래도 네이버 검색 노출이 잘 돼서 추가 기회가 생기는 게 장점입니다. ${D}`,
    pros: "네이버 검색 상위 노출, 안정적 수익",
    cons: "선정까지 오래 걸림, 글쓰기 지속적으로 필요",
    recommend: true,
  },

  // ── 네이버 블로그 (애드포스트) ──
  {
    nickname: "블로그수익러",
    hustle_id: "naver-blog",
    hustle_name: "네이버 블로그 (애드포스트)",
    income_range: "30_to_50",
    weekly_hours: 10,
    difficulty: 2,
    satisfaction: 4,
    title: "하루 방문자 800명, 월 수익 35만원 달성",
    content: `육아 정보 블로그 운영 1년 반 만에 하루 방문자 800명, 월 수익 35만원 됩니다. 애드포스트 광고 수익은 방문자 1000명당 5천~1만원 수준인데, 체험단 원고료가 훨씬 커요. 체험단 1건에 3~10만원 받는 경우도 있어서 수익 비중이 체험단 쪽이 더 높아졌습니다. 꾸준히 포스팅하는 게 핵심이에요. ${D}`,
    pros: "체험단으로 추가 수익 가능, 진입장벽 낮음",
    cons: "방문자 늘리기까지 시간 필요, 꾸준한 포스팅 필수",
    recommend: true,
  },
  {
    nickname: "블로그3년차",
    hustle_id: "naver-blog",
    hustle_name: "네이버 블로그 (애드포스트)",
    income_range: "10_to_30",
    weekly_hours: 7,
    difficulty: 2,
    satisfaction: 3,
    title: "3년 운영해도 월 15만원, 현실적인 이야기",
    content: `맛집·여행 블로그 3년째인데 방문자 400명 수준으로 월 수익 10~15만원이에요. 네이버 알고리즘이 자꾸 바뀌어서 열심히 했다가 방문자 반 토막 난 적도 있어요. 정보성 글 중심으로 가야 검색 유입이 꾸준하고, 광고성 느낌 나는 글은 저품질 처리되더라고요. 부수입으로는 괜찮지만 큰돈 기대는 금물입니다. ${D}`,
    pros: "누구나 시작 가능, 자투리 시간 활용",
    cons: "알고리즘 변화에 취약, 성장 상한선 있음",
    recommend: true,
  },

  // ── 티스토리 블로그 (구글 애드센스) ──
  {
    nickname: "애드센스달성",
    hustle_id: "tistory",
    hustle_name: "티스토리 블로그 (구글 애드센스)",
    income_range: "30_to_50",
    weekly_hours: 12,
    difficulty: 3,
    satisfaction: 4,
    title: "애드센스 승인까지 4개월, 이후 월 40만원",
    content: `IT 정보 블로그로 애드센스 4개월 만에 승인받고, 이후 6개월 뒤 월 40만원 수익 찍었어요. 하루 방문자 2500명 수준입니다. 네이버 블로그보다 글당 수익이 높은 게 장점이에요. 영어권 독자가 섞이면 RPM이 더 높아져요. SEO 공부가 필수이고 초반에 무조건 글 수를 늘려야 합니다. ${D}`,
    pros: "애드센스 단가가 네이버보다 높음, 글 누적되면 패시브 수익",
    cons: "승인까지 오래 걸림, SEO 학습 필요",
    recommend: true,
  },
  {
    nickname: "구글애드센스초보",
    hustle_id: "tistory",
    hustle_name: "티스토리 블로그 (구글 애드센스)",
    income_range: "under_10",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 2,
    title: "승인은 받았는데 방문자가 없어서 수익이 없다",
    content: `티스토리 애드센스 승인까지 3개월 걸렸어요. 그런데 글 50개 올렸는데도 하루 방문자가 50~100명 수준이라 월 수익이 2만원도 안 됩니다. 구글 검색 상위 노출이 생각보다 너무 어려워요. 경쟁 키워드에서 이미 잘 쓴 글들이 많아서 신규 블로그가 치고 들어가기 힘든 구조입니다. ${D}`,
    pros: "한 번 자리잡으면 패시브 수익",
    cons: "구글 SEO 상위 진입이 너무 어려움",
    recommend: false,
  },

  // ── 카카오뷰 ──
  {
    nickname: "카카오뷰운영자",
    hustle_id: "kakao-view",
    hustle_name: "카카오뷰",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 1,
    satisfaction: 2,
    title: "진입장벽 낮은 대신 수익도 낮다",
    content: `카카오뷰 채널 6개월 운영했는데 구독자 1200명에 월 수익 2~3만원이에요. 수익 구조가 카카오 보드 클릭당 적립인데 단가가 너무 낮습니다. 다른 채널 콘텐츠 큐레이션이라 글 쓸 필요 없어서 시간은 적게 들어요. 부업 수익으로는 정말 소액이지만, 다른 SNS 유입 채널로 활용하는 사람들도 있어요. ${D}`,
    pros: "콘텐츠 제작 부담 없음, 진입장벽 최저",
    cons: "수익이 너무 적음, 수익 구조 불투명",
    recommend: false,
  },
  {
    nickname: "카뷰구독자모으기",
    hustle_id: "kakao-view",
    hustle_name: "카카오뷰",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 1,
    satisfaction: 3,
    title: "부업보다는 콘텐츠 큐레이션 연습용으로 좋아요",
    content: `뉴스레터 준비하면서 카카오뷰로 글 큐레이션 연습 중이에요. 수익은 월 1~2만원 수준으로 거의 없다시피 하지만 구독자가 조금씩 늘어나는 재미가 있어요. 하루 30분 정도 뉴스 큐레이션하는 느낌으로 가볍게 하기엔 좋습니다. 수익만 보면 추천은 못 하겠어요. ${D}`,
    pros: "시간 투자 최소화, 글쓰기 부담 없음",
    cons: "수익 매우 낮음, 성장에 한계",
    recommend: false,
  },

  // ── 브런치 작가 ──
  {
    nickname: "브런치에세이스트",
    hustle_id: "brunch",
    hustle_name: "브런치 작가",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 2,
    satisfaction: 4,
    title: "직접 수익은 없지만 책 출판 제안이 왔어요",
    content: `브런치에 에세이 1년간 연재했더니 출판사에서 책 출판 제안이 왔어요. 브런치 자체 수익은 없지만 글이 퀄리티 있으면 출판, 강의, 미디어 기고 등의 기회로 이어집니다. 작가 브랜딩 목적이면 정말 좋은 플랫폼이에요. 단, 빠른 수익을 원하면 맞지 않아요. ${D}`,
    pros: "글쓰기 브랜딩, 출판·강의 등 기회 연결",
    cons: "직접 수익 없음, 성과까지 오래 걸림",
    recommend: true,
  },
  {
    nickname: "글쓰기취미인",
    hustle_id: "brunch",
    hustle_name: "브런치 작가",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 2,
    satisfaction: 3,
    title: "수익보다는 포트폴리오로 활용 중",
    content: `직장인인데 부업 포트폴리오용으로 브런치에 마케팅 인사이트 글 올리고 있어요. 수익은 없지만 링크드인이나 이력서에 '브런치 작가'로 기재하니 프리랜서 마케터 문의가 가끔 들어와요. 글로 돈 버는 직접적인 방법은 아니지만 간접적인 수익화 가능성은 있습니다. ${D}`,
    pros: "전문성 어필, 프리랜서 연결 기회",
    cons: "직접 수익 없음",
    recommend: true,
  },

  // ── 뉴스레터 ──
  {
    nickname: "뉴스레터발행인",
    hustle_id: "newsletter",
    hustle_name: "뉴스레터 (서브스택·스티비)",
    income_range: "30_to_50",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 4,
    title: "구독자 500명에 유료 전환율 10%, 월 40만원",
    content: `IT 트렌드 뉴스레터 1년 운영 중이에요. 무료 구독자 500명 중 50명이 월 9,000원 유료 구독해서 월 45만원 수익이 나요. 스티비로 발행하고 있는데 편집이 쉬워서 좋아요. 처음 구독자 모으는 게 제일 어려운 관문이고, 초반 3개월은 100명도 안 모였습니다. 콘텐츠 차별화가 핵심이에요. ${D}`,
    pros: "충성 독자 기반 안정적 수익, 자유로운 형식",
    cons: "초기 구독자 모집 매우 어려움",
    recommend: true,
  },
  {
    nickname: "뉴스레터시작함",
    hustle_id: "newsletter",
    hustle_name: "뉴스레터 (서브스택·스티비)",
    income_range: "under_10",
    weekly_hours: 6,
    difficulty: 3,
    satisfaction: 3,
    title: "4개월째 구독자 200명, 수익화는 아직",
    content: `재테크 뉴스레터 4개월째인데 구독자 200명이에요. 유료 전환을 아직 못 했고 콘텐츠 기획하고 쓰는 데만 매주 5~6시간 쏟고 있어요. 구독자 1000명은 돼야 유료 전환이 의미있다고 하는데, 거기까지 가는 게 보통 일이 아니네요. 꾸준히 해볼 생각이지만 현실은 쉽지 않아요. ${D}`,
    pros: "글 자산 축적, 본인 브랜딩",
    cons: "구독자 확보 어려움, 수익화까지 오래 걸림",
    recommend: false,
  },

  // ── 스레드 운영 ──
  {
    nickname: "스레드얼리어답터",
    hustle_id: "threads",
    hustle_name: "스레드 (Threads) 운영",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 2,
    satisfaction: 3,
    title: "팔로워 빠르게 모이는데 수익화는 아직 불명확",
    content: `인스타그램 연동으로 스레드 팔로워 3000명 빠르게 모았어요. 근데 스레드 자체 수익화 프로그램이 없어서 직접 돈 벌기는 어렵습니다. 인스타나 블로그로 트래픽 유도하거나 본인 서비스 홍보 채널로 쓰는 게 현실적이에요. 장기적으로 수익화 기능이 생기면 모를까 지금은 보조 채널 정도로 활용 중입니다. ${D}`,
    pros: "인스타 연동으로 빠른 초기 성장",
    cons: "수익화 기능 미흡, 독자적 수익 없음",
    recommend: false,
  },
  {
    nickname: "스레드마케터",
    hustle_id: "threads",
    hustle_name: "스레드 (Threads) 운영",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 1,
    satisfaction: 3,
    title: "내 강의 홍보 채널로 활용 중",
    content: `온라인 강의 판매하는데 스레드를 홍보 채널로 쓰고 있어요. 하루 1~2개 짧은 인사이트 글 올리고 강의 링크 연결하니 월 5~10명 정도 강의로 유입됩니다. 스레드 자체 수익은 없지만 간접 수익 채널로는 나쁘지 않아요. 글쓰기 부담도 적고요. ${D}`,
    pros: "간편한 운영, 다른 채널 유입 역할",
    cons: "직접 수익 없음",
    recommend: true,
  },

  // ── 쿠팡파트너스 ──
  {
    nickname: "파트너스고수",
    hustle_id: "coupang-partners",
    hustle_name: "쿠팡파트너스",
    income_range: "50_to_100",
    weekly_hours: 5,
    difficulty: 1,
    satisfaction: 5,
    title: "블로그에 링크만 달았는데 월 70만원 들어와요",
    content: `네이버 블로그에 육아용품 리뷰 올리면서 쿠팡파트너스 링크 달았더니 방문자 증가와 함께 수익이 올라갔어요. 하루 방문자 500~700명에 월 60~80만원 수익이 나옵니다. 쿠팡파트너스는 링크 클릭 후 24시간 내 어떤 상품을 사든 수수료가 붙어서 생각보다 수익이 높아요. 블로그 있으면 가장 먼저 시작할 부업이에요. ${D}`,
    pros: "시작이 쉽고 수익이 빠름, 수수료 구조가 유리",
    cons: "트래픽이 없으면 수익도 없음",
    recommend: true,
  },
  {
    nickname: "쿠팡링크공유중",
    hustle_id: "coupang-partners",
    hustle_name: "쿠팡파트너스",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 1,
    satisfaction: 3,
    title: "카카오톡 공유로 월 3만원, 소소하게 시작",
    content: `블로그 없이 카카오톡 오픈채팅방에 쿠팡파트너스 링크 공유하는 방식으로 시작했어요. 월 2~4만원 수익인데 투자한 시간이 없으니 나쁘지 않아요. 근데 진짜 수익을 올리려면 블로그나 SNS 채널이 필수인 것 같아요. 채널 없이는 한계가 명확합니다. ${D}`,
    pros: "즉시 시작 가능, 채널 없어도 소액은 가능",
    cons: "채널 없으면 수익 한계 명확",
    recommend: true,
  },

  // ── 링크프라이스 ──
  {
    nickname: "링크프라이스유저",
    hustle_id: "linkprice",
    hustle_name: "링크프라이스",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 2,
    satisfaction: 3,
    title: "쿠팡파트너스 병행하면 수익 다각화 돼요",
    content: `쿠팡파트너스 외에 링크프라이스도 같이 사용 중이에요. 패션, 여행, 금융 등 쿠팡이 없는 카테고리 상품들 링크를 걸 수 있어서 유용합니다. 단독으로 쓰면 월 5~10만원 수준이지만 쿠팡파트너스랑 같이 쓰면 총 수익이 올라가요. 여러 제휴 플랫폼 병행 운영을 권장합니다. ${D}`,
    pros: "쿠팡 외 다양한 브랜드 링크 가능, 수익 다각화",
    cons: "단독으로는 수익 낮음",
    recommend: true,
  },
  {
    nickname: "제휴마케팅입문자",
    hustle_id: "linkprice",
    hustle_name: "링크프라이스",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 2,
    satisfaction: 2,
    title: "플랫폼이 좀 복잡하고 수익 확인이 불편해요",
    content: `링크프라이스 써봤는데 인터페이스가 쿠팡파트너스보다 복잡하고 수익 추적이 직관적이지 않아요. 수익도 쿠팡파트너스보다 낮고요. 블로그 트래픽이 어느 정도 있어야 의미있고, 처음 제휴마케팅 시작하는 분들은 쿠팡파트너스부터 익히는 게 나을 것 같아요. ${D}`,
    pros: "다양한 브랜드 선택 가능",
    cons: "인터페이스 복잡, 쿠팡파트너스 대비 수익 낮음",
    recommend: false,
  },

  // ── 텐핑 ──
  {
    nickname: "텐핑수익자",
    hustle_id: "tenping",
    hustle_name: "텐핑",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 1,
    satisfaction: 3,
    title: "SNS에 광고 공유만 해도 돈이 들어와요",
    content: `인스타그램에 텐핑 캠페인 공유하면서 월 3~8만원 수익 내고 있어요. 팔로워가 많을수록 수익이 올라가고, 저는 팔로워 2000명 수준에서 이 정도 나옵니다. 캠페인 선택지가 다양해서 제 계정 콘셉트에 맞는 광고를 고를 수 있어요. 시간 투자 대비 소소한 수익이지만 채널이 있으면 해볼 만해요. ${D}`,
    pros: "간단한 공유만으로 수익, 다양한 캠페인",
    cons: "팔로워 없으면 수익 미미",
    recommend: true,
  },
  {
    nickname: "SNS광고공유러",
    hustle_id: "tenping",
    hustle_name: "텐핑",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 1,
    satisfaction: 2,
    title: "팔로워 없으면 정말 쥐꼬리 수익",
    content: `팔로워 500명 계정으로 텐핑 해봤는데 한 달에 5천원도 안 됩니다. 캠페인마다 성과 기준(클릭, 구매 등)이 달라서 단순 공유로는 수익이 거의 없어요. 어느 정도 팔로워가 있어야 의미있는 수익이 나오는 구조입니다. ${D}`,
    pros: "누구나 시작 가능",
    cons: "팔로워 없으면 수익 없다시피 함",
    recommend: false,
  },

  // ── 아마존 어소시에이트 ──
  {
    nickname: "영어블로거달러수익",
    hustle_id: "amazon-associates",
    hustle_name: "아마존 어소시에이트",
    income_range: "30_to_50",
    weekly_hours: 12,
    difficulty: 3,
    satisfaction: 4,
    title: "영어 블로그로 아마존 어소시에이트 월 $250",
    content: `IT 기기 리뷰 영어 블로그 운영한 지 2년인데 아마존 어소시에이트로 월 200~300달러 벌고 있어요. 한국어 블로그보다 수수료율도 높고 상품 단가가 높아서 같은 클릭수에도 수익이 더 나와요. 영어 쓰는 부담은 있지만 SEO 최적화만 잘 하면 구글 트래픽을 한국보다 더 많이 받을 수 있어요. ${D}`,
    pros: "달러 수익, 한국보다 높은 수수료",
    cons: "영어 콘텐츠 제작 필요, 초기 트래픽 쌓기 어려움",
    recommend: true,
  },
  {
    nickname: "아마존파트너스도전",
    hustle_id: "amazon-associates",
    hustle_name: "아마존 어소시에이트",
    income_range: "under_10",
    weekly_hours: 6,
    difficulty: 3,
    satisfaction: 2,
    title: "가입은 쉬운데 180일 안에 판매 3건 못 하면 계정 삭제됩니다",
    content: `아마존 어소시에이트 가입했다가 180일 안에 판매 3건 기준 못 채워서 계정이 삭제됐어요. 재가입은 가능하지만 초기에 트래픽이 없으면 이 조건 채우기가 쉽지 않아요. 영어 블로그 트래픽이 어느 정도 있는 분께만 추천합니다. 없으면 조건 못 채우고 계정 삭제되는 악순환이에요. ${D}`,
    pros: "글로벌 수요, 높은 단가 상품",
    cons: "초기 판매 조건 달성 어려움, 영어 필수",
    recommend: false,
  },

  // ── 아이라이크픽 ──
  {
    nickname: "아이라이크픽사용자",
    hustle_id: "ilikepick",
    hustle_name: "아이라이크픽",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 1,
    satisfaction: 3,
    title: "캠페인 참여만 해도 소액이지만 꾸준히 들어와요",
    content: `아이라이크픽으로 블로그 체험단, SNS 마케터 활동 병행 중이에요. 월 5~15만원 수준인데 특별히 제작 작업 없이 공유 위주라 시간 투자가 적은 편이에요. 캠페인 종류가 다양해서 제 채널 성격에 맞게 고를 수 있어요. 블로그나 인스타 있으면 같이 하면 좋습니다. ${D}`,
    pros: "진입장벽 낮음, 다양한 캠페인",
    cons: "수익 낮음, 채널 있어야 의미있음",
    recommend: true,
  },
  {
    nickname: "SNS마케터지망",
    hustle_id: "ilikepick",
    hustle_name: "아이라이크픽",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 1,
    satisfaction: 2,
    title: "기대했던 것보다 수익이 너무 낮아요",
    content: `아이라이크픽 3개월 써봤는데 월 3만원 수준이에요. 캠페인 참여 기준도 팔로워, 방문자 조건이 있어서 신규 채널이면 참여 자체가 제한돼요. 채널이 성장한 분들에게는 유용하겠지만 초보 단계에서는 수익이 거의 없어요. ${D}`,
    pros: "병행하기 쉬움",
    cons: "수익 너무 낮음, 채널 조건 필요",
    recommend: false,
  },

  // ── 크몽 ──
  {
    nickname: "크몽디자이너",
    hustle_id: "kmong",
    hustle_name: "크몽",
    income_range: "over_100",
    weekly_hours: 20,
    difficulty: 3,
    satisfaction: 5,
    title: "그래픽 디자인으로 크몽 월 130만원 벌고 있어요",
    content: `회사 다니면서 크몽에서 로고, 상세페이지 디자인 서비스 팔고 있어요. 처음 3개월은 리뷰 없어서 건수가 적었는데 리뷰 10개 쌓이니 자동으로 들어옵니다. 지금은 월 10~15건 작업으로 130만원 정도 수익이에요. 크몽 수수료가 20%라 아깝긴 하지만 클라이언트 구하는 수고를 생각하면 납득해요. ${D}`,
    pros: "클라이언트 유입 자동, 리뷰 쌓이면 안정적 수입",
    cons: "수수료 최대 20%, 초기 리뷰 없으면 수주 어려움",
    recommend: true,
  },
  {
    nickname: "크몽번역가",
    hustle_id: "kmong",
    hustle_name: "크몽",
    income_range: "30_to_50",
    weekly_hours: 10,
    difficulty: 3,
    satisfaction: 4,
    title: "영한 번역으로 월 35만원, 부업으로 딱이에요",
    content: `영어 번역 서비스 크몽에 올렸어요. 처음엔 건당 2만원으로 싸게 시작해서 리뷰 모으고 지금은 건당 5~8만원 받습니다. 월 4~6건 정도 들어오고 수익은 35만원 수준이에요. 번역이라 본인 시간에 자유롭게 작업할 수 있어서 직장인 부업으로 좋아요. 단, 처음 리뷰 없는 기간이 좀 답답했습니다. ${D}`,
    pros: "시간 자유, 전문 스킬 있으면 안정적 수입",
    cons: "초기 리뷰 쌓기까지 시간 필요",
    recommend: true,
  },

  // ── 숨고 ──
  {
    nickname: "숨고레슨러",
    hustle_id: "soomgo",
    hustle_name: "숨고",
    income_range: "50_to_100",
    weekly_hours: 12,
    difficulty: 2,
    satisfaction: 4,
    title: "피아노 레슨으로 숨고 통해 월 80만원",
    content: `숨고에 피아노 레슨 올렸는데 지역 기반이라 오프라인 레슨 연결이 잘 돼요. 한 달에 신규 학생 2~3명씩 연결되고 기존 학생 유지되니까 지금은 월 70~90만원 수익이에요. 초기에 견적 보내는 게 포인트를 소모해서 좀 아깝긴 한데, 그만큼 질 높은 고객이 오는 것 같아요. ${D}`,
    pros: "지역 고객 연결 용이, 다양한 서비스 등록 가능",
    cons: "견적 제안 시 포인트 소모",
    recommend: true,
  },
  {
    nickname: "숨고청소전문가",
    hustle_id: "soomgo",
    hustle_name: "숨고",
    income_range: "30_to_50",
    weekly_hours: 15,
    difficulty: 2,
    satisfaction: 3,
    title: "경쟁이 치열해서 견적 보내도 선택 안 받을 때가 많아요",
    content: `집 청소 서비스로 숨고 6개월 했어요. 견적 요청이 오면 여러 업체가 동시에 경쟁해서 가격 낮춰야 선택받는 경우가 많아요. 포인트 소모해서 견적 보냈는데 선택 못 받으면 손해예요. 리뷰 쌓은 후로는 선택률이 올라갔습니다. 경쟁이 적은 틈새 서비스가 유리해요. ${D}`,
    pros: "오프라인 서비스 연결 용이",
    cons: "견적 경쟁 치열, 포인트 소모",
    recommend: true,
  },

  // ── 위시켓 ──
  {
    nickname: "위시켓프리랜서",
    hustle_id: "wishket",
    hustle_name: "위시켓",
    income_range: "over_100",
    weekly_hours: 25,
    difficulty: 4,
    satisfaction: 4,
    title: "프론트엔드 개발로 위시켓 프로젝트 월 200만원",
    content: `React 개발자인데 위시켓으로 사이드 프로젝트 수주합니다. 건당 300~500만원 프로젝트를 1~2개월에 하나씩 진행하는데 월 환산 150~200만원 수준이에요. 포트폴리오가 좋으면 제안이 꾸준히 들어와요. 경쟁이 있긴 하지만 개발 스킬 있으면 확실한 수익이에요. 본업과 병행은 체력적으로 힘들기도 합니다. ${D}`,
    pros: "높은 단가, IT 스킬 있으면 안정적 수익",
    cons: "포트폴리오 없으면 수주 어려움, 체력 소모 많음",
    recommend: true,
  },
  {
    nickname: "위시켓초보개발자",
    hustle_id: "wishket",
    hustle_name: "위시켓",
    income_range: "30_to_50",
    weekly_hours: 15,
    difficulty: 4,
    satisfaction: 3,
    title: "경력 2년차인데 경쟁에서 밀리는 게 현실",
    content: `개발 경력 2년인데 위시켓에서 프로젝트 따기가 생각보다 힘들어요. 경력 5년+ 분들과 경쟁해야 하니 가격을 낮춰야 선택받고, 그러면 수익이 그다지 높지 않아요. 소규모 프로젝트로 리뷰부터 쌓는 전략으로 가고 있는데 아직 안정적이진 않습니다. ${D}`,
    pros: "IT 스킬 있으면 기회는 있음",
    cons: "경력 적으면 경쟁 불리, 수주 불안정",
    recommend: true,
  },

  // ── 프리모아 ──
  {
    nickname: "프리모아디자이너",
    hustle_id: "freemoa",
    hustle_name: "프리모아",
    income_range: "over_100",
    weekly_hours: 20,
    difficulty: 4,
    satisfaction: 4,
    title: "UI/UX 디자인 프리모아로 부업 월 150만원",
    content: `UI 디자이너인데 프리모아로 단기 프로젝트 수주 중이에요. 위시켓이랑 유사하지만 디자인 쪽 프로젝트는 프리모아가 더 많은 것 같아요. 건당 200~400만원 프로젝트 2개월에 1건씩 하면 월 100~150만원 나와요. 원격 가능한 프로젝트가 많아서 직장인 부업으로 좋습니다. ${D}`,
    pros: "원격 프로젝트 많음, 높은 단가",
    cons: "포트폴리오 필수, 경쟁 있음",
    recommend: true,
  },
  {
    nickname: "프리모아사용후기",
    hustle_id: "freemoa",
    hustle_name: "프리모아",
    income_range: "50_to_100",
    weekly_hours: 12,
    difficulty: 4,
    satisfaction: 3,
    title: "위시켓이랑 병행하는 게 수주율 높아요",
    content: `프리모아랑 위시켓 동시에 사용 중이에요. 두 플랫폼에서 프로젝트 제안 받으면 수주 기회가 늘어나요. 각각 단독으론 수주 텀이 길어서 수입이 불안정한데 병행하니 평균적으로 월 60~80만원 수익이 나요. 플랫폼 수수료가 좀 아깝지만 클라이언트 찾는 시간 아끼는 게 낫다고 판단했어요. ${D}`,
    pros: "다양한 프로젝트 제안, 원격 가능",
    cons: "단독 수주 불안정, 수수료 발생",
    recommend: true,
  },

  // ── 업워크 ──
  {
    nickname: "업워크달러버는중",
    hustle_id: "upwork",
    hustle_name: "업워크 (해외 프리랜서)",
    income_range: "over_100",
    weekly_hours: 20,
    difficulty: 5,
    satisfaction: 5,
    title: "영어 되면 진짜 달러 쏟아진다, 월 $450",
    content: `영어 가능한 프론트엔드 개발자인데 업워크로 월 400~500달러 벌고 있어요. 처음 3개월은 제로에서 시작해서 $3~$5짜리 소규모 작업으로 리뷰 쌓고, 지금은 시간당 $25~$35 받아요. 국내보다 훨씬 단가가 높고 달러 환차익도 있어요. 다만 영어 소통이 자연스러워야 하고 초반 리뷰 없을 때가 가장 힘들었어요. ${D}`,
    pros: "달러 수입, 국내 대비 높은 단가",
    cons: "영어 필수, 초반 리뷰 없을 때 수주 어려움",
    recommend: true,
  },
  {
    nickname: "업워크도전실패",
    hustle_id: "upwork",
    hustle_name: "업워크 (해외 프리랜서)",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 5,
    satisfaction: 2,
    title: "제안서 20개 보냈는데 단 1건도 수주 못 했다",
    content: `개발 스킬은 있는데 영어 제안서 쓰는 게 너무 어색했어요. 비슷한 조건의 인도·필리핀 프리랜서들이 더 싼 단가로 제안하니 경쟁이 안 돼요. 업워크는 영어 커뮤니케이션이 자연스럽게 될 정도는 돼야 의미가 있는 것 같아요. 영어 자신 없으면 국내 플랫폼이 낫습니다. ${D}`,
    pros: "기회는 무한대",
    cons: "영어 장벽, 글로벌 저단가 경쟁",
    recommend: false,
  },

  // ── 클래스101 ──
  {
    nickname: "클101드로잉강사",
    hustle_id: "class101",
    hustle_name: "클래스101",
    income_range: "over_100",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 5,
    title: "수채화 강의 올리고 첫 달 120만원, 지금도 월 80만원",
    content: `수채화 강의 클래스101에 올렸는데 오픈 첫 달 수강생 80명 등록해서 120만원 수익이 나왔어요. 지금은 시간이 지나서 월 60~80만원 수준이지만 촬영 끝낸 강의에서 자동으로 수익이 나오는 게 너무 좋아요. 강의 제작에 3주 정도 걸렸는데 이후 거의 손댈 게 없어요. 패시브 인컴의 정석이에요. ${D}`,
    pros: "패시브 인컴, 한 번 제작으로 지속 수익",
    cons: "강의 제작에 초기 시간·장비 투자 필요",
    recommend: true,
  },
  {
    nickname: "클래스101수익감소중",
    hustle_id: "class101",
    hustle_name: "클래스101",
    income_range: "10_to_30",
    weekly_hours: 3,
    difficulty: 3,
    satisfaction: 3,
    title: "오픈 초기엔 좋았는데 시간 지나면 수익 급감해요",
    content: `요가 강의 올리고 첫 달 70만원 나왔는데 6개월 지나니 월 15만원 수준으로 확 떨어졌어요. 클래스101 특성상 신규 강의 노출이 우선이라 오래된 강의는 묻히는 것 같아요. 꾸준한 수익 원하면 강의를 계속 새로 올려야 하는 구조인데, 제작이 생각보다 힘들어요. ${D}`,
    pros: "초기 수익은 좋음",
    cons: "시간 지나면 수익 급감, 지속적 신규 강의 필요",
    recommend: true,
  },

  // ── 탈잉 ──
  {
    nickname: "탈잉튜터5년",
    hustle_id: "taling",
    hustle_name: "탈잉",
    income_range: "50_to_100",
    weekly_hours: 10,
    difficulty: 3,
    satisfaction: 4,
    title: "포토샵 튜터로 탈잉 월 60만원 꾸준해요",
    content: `포토샵·일러스트레이터 강의 탈잉에서 3년째 하고 있어요. 처음엔 수강생 모으기 힘들었는데 리뷰 30개 넘고 나서 자동으로 들어오기 시작했습니다. 온라인 강의 위주로 바꾸니 지역 제한 없이 월 50~70만원 꾸준하게 나와요. 자신 있는 기술 하나 있으면 탈잉 추천합니다. ${D}`,
    pros: "리뷰 쌓이면 안정적, 온라인으로 지역 제한 없음",
    cons: "초기 수강생 모집 어려움",
    recommend: true,
  },
  {
    nickname: "탈잉초보튜터",
    hustle_id: "taling",
    hustle_name: "탈잉",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 3,
    satisfaction: 2,
    title: "등록은 쉬운데 수강생 모으기가 너무 어렵다",
    content: `영어회화 강의 탈잉에 올렸는데 4개월간 수강생이 3명밖에 없어요. 이미 잘 나가는 강사들이 많아서 신규 강사는 노출도 잘 안 되는 것 같아요. 탈잉 외부에서 직접 홍보해야 하는데 그게 더 힘드네요. 기존에 팔로워가 있는 분이 아니면 초반이 정말 힘들어요. ${D}`,
    pros: "등록 간편",
    cons: "신규 강사 노출 불리, 초기 수강생 모집 어려움",
    recommend: false,
  },

  // ── 온라인 과외 ──
  {
    nickname: "수학과외선생님",
    hustle_id: "online-tutoring",
    hustle_name: "온라인 과외 (과외앱)",
    income_range: "50_to_100",
    weekly_hours: 12,
    difficulty: 2,
    satisfaction: 5,
    title: "수학 과외 주 3명에 월 80만원, 최고의 부업",
    content: `수학과외닷컴, 아이캔으로 학생 구해서 주 3명 가르치고 있어요. 시간당 4~6만원 받으니 주 12시간에 월 75~80만원 수익이에요. 비대면 과외라 이동 시간 없이 집에서 가능하고 스케줄 조절도 자유로워요. 본업보다 시급이 높아서 오히려 과외를 더 늘리고 싶을 정도예요. ${D}`,
    pros: "높은 시급, 스케줄 자유, 이동 없음",
    cons: "학생 이탈 시 수입 불안정",
    recommend: true,
  },
  {
    nickname: "영어과외시작함",
    hustle_id: "online-tutoring",
    hustle_name: "온라인 과외 (과외앱)",
    income_range: "30_to_50",
    weekly_hours: 8,
    difficulty: 2,
    satisfaction: 4,
    title: "처음 학생 구하기가 관건, 이후엔 소개로 이어져요",
    content: `영어 회화 과외 앱으로 학생 처음 구하는 데 2주 걸렸어요. 첫 학생이 소개해줘서 금방 3명 됐습니다. 지금 월 35~45만원 수익인데 시간당 3만 5천원 받아요. 과외 앱 수수료가 좀 있지만 직접 홍보 안 해도 되니 편해요. 첫 학생 구하면 이후는 소개로 잘 늘어납니다. ${D}`,
    pros: "소개로 학생 확장, 높은 시급",
    cons: "첫 학생 구하기 초반 어려움",
    recommend: true,
  },

  // ── 유데미 ──
  {
    nickname: "유데미강의판매자",
    hustle_id: "udemy",
    hustle_name: "유데미 (Udemy) 강의 등록",
    income_range: "30_to_50",
    weekly_hours: 3,
    difficulty: 3,
    satisfaction: 4,
    title: "한국어 강의도 되고 달러로 입금돼요",
    content: `파이썬 기초 강의 유데미에 올렸어요. 한국어 강의인데 해외 한국인 학습자들이 구매해줘서 달러 수익이 나와요. 강의 오픈 초기 할인 쿠폰 뿌리면 리뷰 빠르게 쌓이고, 이후 자연 구매가 들어옵니다. 월 30~50만원 패시브 수익인데 처음 강의 제작만 고생하면 이후 거의 손댈 게 없어요. ${D}`,
    pros: "달러 패시브 수익, 한국어 강의 가능",
    cons: "초기 제작 시간 투자, 할인 판매로 단가 낮음",
    recommend: true,
  },
  {
    nickname: "유데미수익미미함",
    hustle_id: "udemy",
    hustle_name: "유데미 (Udemy) 강의 등록",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 3,
    satisfaction: 2,
    title: "유데미 할인 정책 때문에 수익이 너무 낮아요",
    content: `포토그래피 강의 올렸는데 유데미가 상시 할인을 90% 이상 때리는 정책이라 강의 가격이 $10~$15 수준으로 낮아요. 거기서 유데미가 수수료 가져가면 실 수익이 건당 $2~$4 수준이에요. 판매량이 많아야 의미있는데 마케팅 안 하면 판매가 잘 안 됩니다. ${D}`,
    pros: "패시브 인컴 구조",
    cons: "강제 할인 정책으로 단가 매우 낮음",
    recommend: false,
  },

  // ── 스마트스토어 ──
  {
    nickname: "스마트스토어성공",
    hustle_id: "smart-store",
    hustle_name: "스마트스토어",
    income_range: "over_100",
    weekly_hours: 25,
    difficulty: 3,
    satisfaction: 4,
    title: "위탁판매로 월 순수익 120만원 달성",
    content: `도매꾹에서 상품 소싱해서 스마트스토어 위탁판매 하고 있어요. 상품 등록 초반에 광고비 좀 들었는데 검색 상위 올라간 상품들은 광고 없이도 팔려요. 월 매출 600만원에 순수익 120만원 수준입니다. CS 대응이 제일 힘들고, 반품·교환 처리가 생각보다 시간 잡아먹어요. ${D}`,
    pros: "재고 없이 위탁으로 시작 가능, 네이버 검색 유입",
    cons: "CS 부담, 초기 광고비 필요",
    recommend: true,
  },
  {
    nickname: "스마트스토어실패후기",
    hustle_id: "smart-store",
    hustle_name: "스마트스토어",
    income_range: "under_10",
    weekly_hours: 10,
    difficulty: 3,
    satisfaction: 2,
    title: "광고비만 날리고 3개월 만에 포기했어요",
    content: `스마트스토어 3개월 운영하다가 포기했어요. 광고 없이는 판매가 거의 없고, 광고 돌리면 광고비가 수익 다 잡아먹더라고요. 이미 잘 팔리는 상품은 경쟁이 너무 심하고, 틈새 상품 찾는 게 생각보다 어려워요. 상품 기획력과 마케팅 없이는 쉽지 않은 사업이에요. ${D}`,
    pros: "진입장벽 낮음",
    cons: "광고비 부담, 상품 기획 없으면 매출 없음",
    recommend: false,
  },

  // ── 쿠팡 로켓그로스 ──
  {
    nickname: "로켓그로스판매자",
    hustle_id: "coupang-rocket",
    hustle_name: "쿠팡 로켓그로스",
    income_range: "over_100",
    weekly_hours: 10,
    difficulty: 3,
    satisfaction: 4,
    title: "CS·배송 쿠팡이 해주니 운영이 정말 편해요",
    content: `쿠팡 로켓그로스로 주방용품 판매 중이에요. CS와 배송을 쿠팡이 다 해주니 운영 부담이 스마트스토어 대비 훨씬 낮아요. 월 순수익 130만원 정도인데 수수료가 높아서 마진율은 낮아요. 그래도 편의성이 너무 좋아서 계속 하고 있어요. 재고 입고가 빠르게 소진되면 품절 관리가 좀 필요합니다. ${D}`,
    pros: "CS·배송 쿠팡 처리, 운영 편의성",
    cons: "수수료 높음, 재고 관리 필요",
    recommend: true,
  },
  {
    nickname: "쿠팡로켓초보",
    hustle_id: "coupang-rocket",
    hustle_name: "쿠팡 로켓그로스",
    income_range: "10_to_30",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 3,
    title: "수수료가 생각보다 많이 빠져나가요",
    content: `쿠팡 로켓그로스 6개월 했는데 수수료가 카테고리마다 다르지만 꽤 높아요. 마진 계산 잘 못 하고 시작했다가 매출은 있어도 실수익이 별로 없는 경험을 했어요. 수수료, 입고비, 반품비 다 계산하고 시작해야 합니다. 지금은 마진 잘 나오는 상품 소수 집중으로 바꿨어요. ${D}`,
    pros: "쿠팡 로켓배지로 판매량 높음",
    cons: "수수료 높음, 수익 계산 꼼꼼히 해야 함",
    recommend: true,
  },
];

async function insertReviews() {
  console.log(`총 ${reviews.length}개 후기 삽입 시작...`);

  let successCount = 0;
  let errorCount = 0;

  for (const review of reviews) {
    const { error } = await supabase.from("reviews").insert({
      nickname: review.nickname,
      hustle_id: review.hustle_id,
      hustle_name: review.hustle_name,
      income_range: review.income_range,
      weekly_hours: review.weekly_hours,
      difficulty: review.difficulty,
      satisfaction: review.satisfaction,
      title: review.title,
      content: review.content,
      pros: review.pros,
      cons: review.cons,
      recommend: review.recommend,
      likes: 0,
      proof_image_url: null,
      kakao_user_id: null,
    });

    if (error) {
      console.error(`❌ 오류 [${review.hustle_id}]:`, error.message);
      errorCount++;
    } else {
      console.log(`✅ 삽입 완료: [${review.hustle_id}] ${review.title}`);
      successCount++;
    }
  }

  console.log(`\n완료: 성공 ${successCount}건, 실패 ${errorCount}건`);
}

insertReviews();
