import { config } from "dotenv";
config({ path: ".env.local", override: true });

import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const D = "※ 이 후기는 인터넷 공개 정보를 바탕으로 작성되었습니다";

interface ReviewInsert {
  nickname: string;
  hustle_id: string;
  hustle_name: string;
  income_range: string;
  weekly_hours: number;
  difficulty: number;
  satisfaction: number;
  title: string;
  content: string;
  pros: string;
  cons: string;
  recommend: boolean;
}

const reviews: ReviewInsert[] = [
  // ── 에이블리 셀러 ──
  {
    nickname: "에이블리패션셀러",
    hustle_id: "ably-seller",
    hustle_name: "에이블리 셀러",
    income_range: "50_to_100",
    weekly_hours: 15,
    difficulty: 3,
    satisfaction: 4,
    title: "여성 패션 소호몰로 에이블리 월 70만원 수익",
    content: `여성 의류 소량 제작해서 에이블리에 올리고 있어요. 입점 심사가 있어서 퀄리티 낮은 상품은 힘들지만, 일단 들어가면 에이블리 특성상 20~30대 여성 고객이 많아서 잘 팔려요. 월 매출 300만원에 순수익 65~75만원이에요. 신상품 주기적으로 올려줘야 노출이 유지됩니다. ${D}`,
    pros: "타겟 고객층 명확, 충성 고객 많음",
    cons: "주기적 신상품 업로드 필요, 재고 관리",
    recommend: true,
  },
  {
    nickname: "에이블리입점후기",
    hustle_id: "ably-seller",
    hustle_name: "에이블리 셀러",
    income_range: "10_to_30",
    weekly_hours: 10,
    difficulty: 3,
    satisfaction: 3,
    title: "입점은 됐는데 노출이 안 되면 의미없어요",
    content: `에이블리 입점 심사 2주 걸렸어요. 입점하고 나서 처음엔 노출이 거의 없어서 월 판매 2~3건 수준이었어요. 에이블리 내부 광고를 써야 노출이 늘어나는데 광고비가 수익을 다 먹어요. 초기 인지도 없는 브랜드는 광고 없이 자연 유입만으로는 정말 힘들어요. ${D}`,
    pros: "입점 후 에이블리 고객 접근 가능",
    cons: "초기 노출 없음, 광고비 부담",
    recommend: false,
  },

  // ── 아마존 FBA ──
  {
    nickname: "아마존FBA운영자",
    hustle_id: "amazon-fba",
    hustle_name: "아마존 FBA",
    income_range: "over_100",
    weekly_hours: 15,
    difficulty: 5,
    satisfaction: 4,
    title: "초기 자본 500만원 투자하고 6개월 뒤 월 200만원",
    content: `아마존 FBA 시작할 때 상품 소싱, 배송비, FBA 수수료 등 초기에 500만원 정도 들었어요. 6개월 공부하고 적용해서 지금은 월 순수익 180~220만원이에요. 달러 수입이라 환율 혜택도 있어요. 상품 선정이 가장 중요하고, 잘못된 상품 고르면 재고 손실이 커요. 진입장벽이 높지만 성공하면 큰 수익이에요. ${D}`,
    pros: "달러 수입, 배송·CS 아마존 처리",
    cons: "초기 자본 많이 필요, 학습 곡선 가파름",
    recommend: true,
  },
  {
    nickname: "아마존FBA실패담",
    hustle_id: "amazon-fba",
    hustle_name: "아마존 FBA",
    income_range: "under_10",
    weekly_hours: 10,
    difficulty: 5,
    satisfaction: 1,
    title: "상품 잘못 골라서 300만원 날렸습니다",
    content: `아마존 FBA 처음 시도했다가 상품 경쟁이 너무 심한 카테고리 고르는 바람에 재고가 안 팔리고 FBA 창고비만 나가서 결국 300만원 손실 봤어요. 상품 리서치 없이 '잘 될 것 같다'는 감으로 시작하면 안 됩니다. 충분한 공부와 소규모 테스트부터 시작해야 해요. ${D}`,
    pros: "성공하면 큰 수익",
    cons: "상품 선정 실패 시 큰 손실, 높은 진입 난이도",
    recommend: false,
  },

  // ── 알리 드롭쉬핑 ──
  {
    nickname: "드롭쉬핑도전자",
    hustle_id: "aliexpress-dropshipping",
    hustle_name: "알리 드롭쉬핑",
    income_range: "10_to_30",
    weekly_hours: 10,
    difficulty: 3,
    satisfaction: 3,
    title: "재고 없이 시작 가능하지만 배송이 문제예요",
    content: `알리에서 상품 찾아서 스마트스토어에 올리는 드롭쉬핑 해봤어요. 재고 없이 시작할 수 있어서 초기 투자가 적어요. 근데 배송이 2~3주 걸리니까 고객 불만이 많고 반품 처리도 복잡해요. 월 수익 15~25만원인데 CS 대응 시간이 많이 들어서 시급 따지면 그다지 높지 않아요. ${D}`,
    pros: "재고 없이 시작 가능, 초기 투자 적음",
    cons: "배송 지연 이슈, CS 부담, 품질 불안정",
    recommend: false,
  },
  {
    nickname: "알리드롭쉬핑중단",
    hustle_id: "aliexpress-dropshipping",
    hustle_name: "알리 드롭쉬핑",
    income_range: "under_10",
    weekly_hours: 6,
    difficulty: 3,
    satisfaction: 2,
    title: "배송 지연으로 별점 1점 테러 맞고 스토어 망했어요",
    content: `드롭쉬핑 6개월 했다가 알리 배송 2~4주 지연으로 고객 불만이 쌓여서 별점이 2점대로 내려갔어요. 스마트스토어 페널티를 받고 노출이 급감해서 결국 포기했습니다. 배송 시간 제어가 안 되는 게 드롭쉬핑의 치명적 약점이에요. 국내 배송 가능한 상품으로 가야 합니다. ${D}`,
    pros: "초기 비용 없음",
    cons: "배송 문제로 계정 신뢰도 하락 위험",
    recommend: false,
  },

  // ── 인스타그램 쇼핑몰 ──
  {
    nickname: "인스타쇼핑몰운영",
    hustle_id: "instagram-shop",
    hustle_name: "인스타그램 쇼핑몰",
    income_range: "30_to_50",
    weekly_hours: 15,
    difficulty: 3,
    satisfaction: 4,
    title: "팔로워 키우면서 의류 판매, 월 40만원 수익",
    content: `소량 제작 의류를 인스타그램에서 직접 판매 중이에요. 플랫폼 수수료 없이 직거래라 마진율이 높아요. 팔로워 3500명에 월 판매 20~30건, 순수익 35~45만원이에요. 콘텐츠 퀄리티가 판매와 직결되니까 사진, 영상 신경 써야 해요. 팔로워 늘리는 게 쉽지 않지만 브랜드 구축 측면에서 좋아요. ${D}`,
    pros: "플랫폼 수수료 없음, 직거래로 높은 마진",
    cons: "팔로워 키우는 데 오래 걸림, 콘텐츠 제작 필수",
    recommend: true,
  },
  {
    nickname: "인스타몰포기함",
    hustle_id: "instagram-shop",
    hustle_name: "인스타그램 쇼핑몰",
    income_range: "under_10",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 2,
    title: "팔로워 없으면 쇼핑몰 기능 아무 의미 없어요",
    content: `인스타 쇼핑 기능 설정하고 상품 올렸는데 팔로워가 800명 수준이라 판매가 한 달에 1~2건이에요. 인스타 알고리즘이 신규 계정에게 노출을 거의 안 줘서 팔로워 늘리기가 너무 힘들어요. 팔로워 최소 5000명은 있어야 의미있는 판매가 될 것 같아요. ${D}`,
    pros: "수수료 없는 직거래",
    cons: "팔로워 없으면 판매 불가, 팔로워 키우기 어려움",
    recommend: false,
  },

  // ── 무신사 스토어 ──
  {
    nickname: "무신사입점브랜드",
    hustle_id: "musinsa-store",
    hustle_name: "무신사 스토어",
    income_range: "over_100",
    weekly_hours: 30,
    difficulty: 5,
    satisfaction: 4,
    title: "무신사 입점만 되면 매출은 따라온다",
    content: `스트릿 캐주얼 브랜드로 무신사 입점 심사 통과했어요. 심사 3번 만에 통과했고 6개월 걸렸습니다. 입점 후 첫 달부터 월 순수익 200만원+ 나왔어요. 무신사 트래픽이 어마어마하니까 입점만 되면 매출이 자연스럽게 따라와요. 다만 심사가 매우 까다롭고 초기 생산 비용이 커요. ${D}`,
    pros: "무신사 트래픽 활용, 입점 후 매출 폭발적",
    cons: "심사 매우 까다로움, 초기 생산 비용 수백만원",
    recommend: true,
  },
  {
    nickname: "무신사심사탈락",
    hustle_id: "musinsa-store",
    hustle_name: "무신사 스토어",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 5,
    satisfaction: 2,
    title: "심사 2번 탈락, 브랜드 없으면 입점 불가에요",
    content: `무신사 입점 두 번 신청했다가 탈락했어요. 개인 셀러 수준으로는 아예 심사를 통과 못 하고, 명확한 브랜드 아이덴티티와 최소 시즌 룩북 수준의 콘텐츠가 있어야 해요. 단순 부업으로 접근하기엔 문턱이 너무 높아요. 브랜드 사업을 본격적으로 하는 분들께나 맞는 것 같아요. ${D}`,
    pros: "입점 시 대규모 매출 가능",
    cons: "일반인 진입 거의 불가능한 수준의 기준",
    recommend: false,
  },

  // ── KREAM 리셀 ──
  {
    nickname: "KREAM리셀러",
    hustle_id: "kream",
    hustle_name: "KREAM 스니커즈·의류 리셀",
    income_range: "30_to_50",
    weekly_hours: 5,
    difficulty: 3,
    satisfaction: 4,
    title: "나이키 발매 줄서기로 월 30~50만원 수익",
    content: `나이키, 뉴발란스 한정판 발매일에 줄서거나 앱에서 응모해서 발매가로 사고 KREAM에서 프리미엄 붙여 팔아요. 건당 수익은 1~5만원 수준이지만 꾸준히 하면 월 30~50만원 나옵니다. 시세 파악이 중요하고, 당첨 확률이 낮은 고가 한정판보다 소액 한정판 여러 개 하는 전략이 안정적이에요. ${D}`,
    pros: "발품만 팔면 수익 확실, 하이리스크 상품 피하면 안정적",
    cons: "경쟁 치열, 당첨 확률 낮음, 초기 자본 필요",
    recommend: true,
  },
  {
    nickname: "KREAM손해봄",
    hustle_id: "kream",
    hustle_name: "KREAM 스니커즈·의류 리셀",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 3,
    satisfaction: 2,
    title: "시세 파악 못 하면 원가 이하로 파는 경우도 있어요",
    content: `초반에 KREAM 리셀 시작했는데 시세 분석 없이 했다가 구매가보다 낮게 팔린 적 있어요. 인기 없는 사이즈나 시즌 지난 상품은 오히려 손해예요. KREAM 수수료도 있고 배송비도 있어서 생각보다 마진이 낮아요. 신발 시장을 잘 아는 분이 아니면 쉽지 않아요. ${D}`,
    pros: "잘 고르면 확실한 수익",
    cons: "시세 모르면 손실 가능, 수수료·배송비 마진 잠식",
    recommend: false,
  },

  // ── 번개장터 리셀 ──
  {
    nickname: "번개장터리셀고수",
    hustle_id: "bunjang-resell",
    hustle_name: "번개장터 리셀",
    income_range: "10_to_30",
    weekly_hours: 6,
    difficulty: 2,
    satisfaction: 4,
    title: "포켓몬 카드 리셀로 월 20만원 용돈벌이",
    content: `편의점 포켓몬 카드 뽑아서 희귀 카드 번개장터에 팔고 있어요. 박스 하나에 5~6만원인데 레어 나오면 2~3배에 팔 수 있어요. 매달 박스 10개 정도 운용하면 월 15~25만원 수익이에요. 운이 따르는 사업이라 편차가 크지만 포켓몬 시장이 꾸준해서 재고 처리는 잘 돼요. ${D}`,
    pros: "소액 자본으로 시작 가능, 진입장벽 낮음",
    cons: "수익 편차 큼, 운에 좌우되는 부분 있음",
    recommend: true,
  },
  {
    nickname: "번개장터피규어셀러",
    hustle_id: "bunjang-resell",
    hustle_name: "번개장터 리셀",
    income_range: "10_to_30",
    weekly_hours: 5,
    difficulty: 2,
    satisfaction: 3,
    title: "한정판 피규어 리셀, 시세 파악이 전부예요",
    content: `굿즈, 한정판 피규어 리셀을 번개장터에서 하고 있어요. 월 10~20만원 수익인데 출시 즉시 구매해서 가격 오를 때 팔면 수익이 나요. 반대로 인기 없는 제품은 원가도 못 건지기 때문에 시장 파악이 중요해요. 취미 겸 부업으로는 괜찮아요. ${D}`,
    pros: "소액으로 시작 가능, 취미와 병행",
    cons: "상품 선정 실패 시 손실",
    recommend: true,
  },

  // ── 당근마켓 중고 플리핑 ──
  {
    nickname: "당근플리핑전문가",
    hustle_id: "used-flip",
    hustle_name: "당근마켓 중고 플리핑",
    income_range: "10_to_30",
    weekly_hours: 8,
    difficulty: 2,
    satisfaction: 4,
    title: "전자기기 수리 후 재판매로 월 25만원",
    content: `당근에서 고장난 전자기기 싸게 사서 수리 후 되팔고 있어요. 아이폰 배터리 교체하면 3~5만원 비용에 10~15만원 마진 나와요. 한 달에 5~8건 정도 하면 25만원 수익이에요. 수리 능력이 없어도 단순 청소·부품 교체 수준으로 시작 가능해요. 눈썰미 있으면 꾸준히 할 수 있어요. ${D}`,
    pros: "소액으로 시작 가능, 마진율 높음",
    cons: "이동 시간, 물건 가져오기 번거로움",
    recommend: true,
  },
  {
    nickname: "당근플리핑시작함",
    hustle_id: "used-flip",
    hustle_name: "당근마켓 중고 플리핑",
    income_range: "under_10",
    weekly_hours: 4,
    difficulty: 2,
    satisfaction: 3,
    title: "시간 대비 수익이 생각만큼 높지 않아요",
    content: `가구 플리핑 해봤는데 생각보다 시간이 많이 들어요. 물건 찾아보는 시간, 직거래 이동 시간, 세척·수리 시간까지 합치면 시간당 수익이 높지 않아요. 월 8~12만원 수준인데 이동 비용 빼면 순수익은 더 낮아요. 자동차 있고 이동이 자유로운 분께 더 맞는 부업이에요. ${D}`,
    pros: "진입장벽 없음",
    cons: "이동 비용, 시간 투자 대비 수익 낮을 수 있음",
    recommend: false,
  },

  // ── 공연 티켓 리셀 ──
  {
    nickname: "티켓리셀러",
    hustle_id: "ticket-resell",
    hustle_name: "공연 티켓 리셀",
    income_range: "10_to_30",
    weekly_hours: 3,
    difficulty: 2,
    satisfaction: 3,
    title: "인기 콘서트 티켓으로 건당 5~10만원 수익",
    content: `인기 아이돌 콘서트 티켓 팬클럽 선예매로 구매해서 못 가게 되면 웃돈 받고 팔아요. 인기 공연은 건당 5~10만원 수익이 나요. 다만 이건 취소된 개인 표 판매인데, 전문 리셀러처럼 대량으로 하면 법적 문제가 될 수 있어요. 소액 부업으로 가끔 하는 수준이에요. ${D}`,
    pros: "소자본으로 즉시 수익",
    cons: "공연 때마다 기회가 불규칙, 법적 주의 필요",
    recommend: true,
  },
  {
    nickname: "티켓리셀실패담",
    hustle_id: "ticket-resell",
    hustle_name: "공연 티켓 리셀",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 2,
    satisfaction: 2,
    title: "취소 수수료 때문에 오히려 손해날 수 있어요",
    content: `티켓 구매하고 팔려고 했는데 공연이 예상보다 인기가 없어서 정가 이하로 팔게 됐어요. 거기에 취소 수수료까지 붙으니 손해였어요. 인기가 확실한 공연이 아니면 오히려 손해볼 수 있고, 판매 안 되면 직접 가야 하는 상황도 생겨요. ${D}`,
    pros: "인기 공연이면 확실한 수익",
    cons: "인기 없는 공연은 손해, 수익 불안정",
    recommend: false,
  },

  // ── 포켓몬 카드 리셀 ──
  {
    nickname: "포켓몬카드투자자",
    hustle_id: "pokemon-card",
    hustle_name: "포켓몬·트레이딩 카드 리셀",
    income_range: "30_to_50",
    weekly_hours: 5,
    difficulty: 3,
    satisfaction: 4,
    title: "포켓몬 카드 박스 투자로 월 35만원",
    content: `포켓몬 카드 신상 박스 나오면 발매일에 구매해서 시세 오를 때 팔고 있어요. 박스 가격 대비 2배 오르면 팔고 빠지는 전략으로 월 30~40만원 수익이에요. 시세 파악은 포켓몬 카드 커뮤니티 참고하고, 빠른 정보가 중요해요. 인기 팩은 출시 직후 일주일 안에 처분하는 게 좋아요. ${D}`,
    pros: "카드 게임 관심 있으면 재미와 수익 동시에",
    cons: "시세 변동 심함, 인기 없는 팩은 손실",
    recommend: true,
  },
  {
    nickname: "포켓몬카드초보",
    hustle_id: "pokemon-card",
    hustle_name: "포켓몬·트레이딩 카드 리셀",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 3,
    satisfaction: 3,
    title: "재미는 있는데 수익은 운에 좌우돼요",
    content: `포켓몬 카드 개봉 콘텐츠랑 겸해서 해봤는데, 레어 뽑기가 안 되면 그냥 소비에 가깝더라고요. 시즌이 지난 카드는 시세가 급락하기도 해서 타이밍이 중요해요. 취미로 즐기면서 소액 수익 노리는 분께는 괜찮지만 진지한 부업으로는 리스크가 있어요. ${D}`,
    pros: "취미와 병행 가능",
    cons: "수익 예측 불가, 운에 크게 좌우",
    recommend: false,
  },

  // ── 캐시슬라이드 ──
  {
    nickname: "잠금화면앱테크",
    hustle_id: "cashslide",
    hustle_name: "캐시슬라이드·잠금화면 앱테크",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 1,
    satisfaction: 3,
    title: "하루 100포인트, 한 달이면 커피 한 잔",
    content: `캐시슬라이드 1년 넘게 쓰고 있어요. 하루 100~150포인트 쌓이고, 한 달이면 3000~4500포인트인데 현금으로 3~4천원이에요. 손가락 하나 안 까딱해도 자동으로 쌓이는 거라 쓰면 손해는 아니에요. 그냥 있는 거 활용하는 수준이지 이걸로 부업 삼기엔 너무 적어요. ${D}`,
    pros: "아무것도 안 해도 자동 적립",
    cons: "수익 너무 적음",
    recommend: true,
  },
  {
    nickname: "앱테크모음러",
    hustle_id: "cashslide",
    hustle_name: "캐시슬라이드·잠금화면 앱테크",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 1,
    satisfaction: 2,
    title: "여러 앱 합쳐도 월 1만원이 한계",
    content: `캐시슬라이드, 버즈런처, 캐시워크 등 잠금화면 앱 3~4개 써봤는데 다 합쳐도 월 8000~12000원이 최대예요. 광고 보는 것도 은근히 귀찮고 배터리 소모도 있어요. 진짜 부업이라고 부르기엔 너무 적은 금액이지만 그냥 켜두는 용도로는 쓸 만해요. ${D}`,
    pros: "시간 투자 없음",
    cons: "수익 미미, 배터리 소모",
    recommend: false,
  },

  // ── 패널나우·설문조사 ──
  {
    nickname: "설문조사러",
    hustle_id: "panel-now",
    hustle_name: "패널나우·설문조사",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 1,
    satisfaction: 3,
    title: "자투리 시간 활용해서 월 5만원 용돈",
    content: `패널나우, 엠브레인 두 개 같이 쓰고 있어요. 출퇴근 시간에 설문 5~10개 하면 하루 2000~3000포인트 쌓이고 한 달에 4~5만원 정도 현금화해요. 설문 주제가 다양해서 지루하진 않아요. 금방 부자 되는 부업은 아니지만 자투리 시간 활용으로는 최고예요. ${D}`,
    pros: "자투리 시간 활용, 쉬운 참여",
    cons: "수익 낮음, 설문 수량 한정적",
    recommend: true,
  },
  {
    nickname: "설문고수",
    hustle_id: "panel-now",
    hustle_name: "패널나우·설문조사",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 1,
    satisfaction: 3,
    title: "여러 플랫폼 병행해야 월 8만원 가능해요",
    content: `패널나우, 마크로밀엠브레인, 리서치뷰 등 설문 플랫폼 4개 병행 중이에요. 다 합쳐서 월 6~8만원 수익이에요. 하나만 하면 설문이 적어서 수익이 적어요. 병행 관리가 귀찮긴 하지만 이동 중에 틈틈이 하면 돼요. 진입장벽이 없어서 부업 입문에 좋아요. ${D}`,
    pros: "진입장벽 없음, 언제 어디서나 가능",
    cons: "단일 플랫폼으론 수익 너무 낮음",
    recommend: true,
  },

  // ── 토스 혜택 ──
  {
    nickname: "토스혜택챙기기",
    hustle_id: "toss-benefit",
    hustle_name: "토스·금융앱 혜택 수익",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 1,
    satisfaction: 3,
    title: "토스 만보기, 행운복권으로 월 2만원 챙기기",
    content: `토스 행운복권, 만보기, 토스피드 매일 빠짐없이 하고 있어요. 한 달 꾸준히 하면 1~2만원 포인트 쌓여요. 카카오페이 이벤트까지 합치면 2~3만원 수준이에요. 생각보다 챙기기 귀찮기도 한데 습관이 되면 자동으로 되더라고요. 부업이라기보단 앱 잘 활용하는 수준이에요. ${D}`,
    pros: "거의 시간 투자 없음",
    cons: "수익 아주 적음",
    recommend: true,
  },
  {
    nickname: "핀테크앱활용중",
    hustle_id: "toss-benefit",
    hustle_name: "토스·금융앱 혜택 수익",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 1,
    satisfaction: 2,
    title: "금융 상품 추천 혜택이 생각보다 짭짤해요",
    content: `토스 친구 추천으로 건당 3~5만원 받는 이벤트가 가끔 있어요. 가족·친구 여러 명 추천하면 일시적으로 20~30만원 벌 수도 있어요. 근데 이건 지속 수익이 아니라 이벤트성이라 계속 의존할 수 없어요. 일반 만보기·복권은 월 1~2만원 수준이에요. ${D}`,
    pros: "추천 이벤트 시 일시적으로 큰 수익",
    cons: "지속 수익 아님, 이벤트 종료 후 수익 없음",
    recommend: true,
  },

  // ── 데이터 라벨링 ──
  {
    nickname: "데이터라벨러",
    hustle_id: "data-labeling",
    hustle_name: "데이터 라벨링",
    income_range: "10_to_30",
    weekly_hours: 10,
    difficulty: 1,
    satisfaction: 3,
    title: "크라우드웍스로 월 15만원, 초보도 바로 시작",
    content: `크라우드웍스에서 이미지 분류, 텍스트 검수 작업 하고 있어요. 특별한 기술 없어도 할 수 있고, 시간 날 때 틈틈이 하면 월 15만원 정도 나와요. 작업 단가가 건당 10~50원 수준이라 시간 대비 수익이 높지는 않아요. 재택으로 할 수 있고 진입장벽이 없어서 부업 입문으로 좋아요. ${D}`,
    pros: "진입장벽 없음, 재택 가능, 즉시 시작",
    cons: "단가 낮음, 시급 계산하면 낮은 편",
    recommend: true,
  },
  {
    nickname: "라벨링하다포기",
    hustle_id: "data-labeling",
    hustle_name: "데이터 라벨링",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 1,
    satisfaction: 2,
    title: "단가가 너무 낮아서 시간 낭비 같아요",
    content: `에이모에서 데이터 라벨링 해봤는데 건당 단가가 너무 낮아요. 집중해서 2시간 해도 5000원 수준이에요. 전문 라벨링 작업으로 가면 단가가 높아지는데 퀄리티 기준도 높아지고 교육도 받아야 해요. 초보 입문으로는 괜찮지만 메인 부업으로는 권장 못 해요. ${D}`,
    pros: "즉시 시작 가능",
    cons: "시급 최저 수준, 단조로운 작업",
    recommend: false,
  },

  // ── 앱·웹 테스트 ──
  {
    nickname: "UX테스터",
    hustle_id: "app-testing",
    hustle_name: "앱·웹 테스트 (유저테스팅)",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 1,
    satisfaction: 3,
    title: "테스트 한 건에 1~2만원, 자투리 시간에 딱",
    content: `유저테스팅 코리아, 오픈유저에서 앱 테스트 참여하고 있어요. 건당 1만~2만원인데 한 달에 2~5건 정도 테스트 기회가 와요. 월 5~8만원 수준이에요. 별다른 스킬 없이 앱 써보고 피드백 주면 되니까 쉬워요. 테스트 기회가 많지 않아서 수익이 한정적이에요. ${D}`,
    pros: "간단한 작업, 건당 수익 나쁘지 않음",
    cons: "기회 수 적음, 월 수익 한정적",
    recommend: true,
  },
  {
    nickname: "웹테스트경험자",
    hustle_id: "app-testing",
    hustle_name: "앱·웹 테스트 (유저테스팅)",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 1,
    satisfaction: 3,
    title: "영어 되면 해외 플랫폼으로 더 많이 벌 수 있어요",
    content: `국내 플랫폼은 테스트 기회가 월 2~3건 수준인데, UserTesting.com(해외) 등록하면 더 자주 기회가 와요. 영어로 진행되고 건당 $10~$20 받아서 월 $50 이상 가능해요. 영어로 말하면서 앱 사용 설명하는 게 처음엔 어색하지만 익숙해지면 쉬워요. ${D}`,
    pros: "해외 플랫폼 병행 시 수익 증가",
    cons: "기회 수 한정, 해외는 영어 필요",
    recommend: true,
  },

  // ── 배당주 투자 ──
  {
    nickname: "배당주장기투자자",
    hustle_id: "stock-dividend",
    hustle_name: "배당주 투자",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 3,
    satisfaction: 4,
    title: "1000만원 투자하고 연 배당금 60만원 받아요",
    content: `배당주 ETF에 1000만원 투자해서 연 6% 배당 수익 받고 있어요. 월 5만원 수준인데 주가 상승까지 더하면 총수익률이 연 10% 넘어요. 배당금 재투자로 복리 효과 노리는 중이에요. 투자 원금이 있어야 하고 단기 수익은 없지만 10년 후를 보면 확실한 자산이에요. ${D}`,
    pros: "안정적 패시브 인컴, 주가 상승 추가 수익",
    cons: "원금 필요, 단기 수익 없음",
    recommend: true,
  },
  {
    nickname: "배당투자초보",
    hustle_id: "stock-dividend",
    hustle_name: "배당주 투자",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 3,
    satisfaction: 3,
    title: "배당률만 보고 샀다가 주가 하락으로 손해",
    content: `고배당주 투자했는데 배당률 높은 기업이 실적 악화로 주가가 30% 떨어졌어요. 배당금은 받았지만 평가손실이 훨씬 커요. 배당주도 기업 실적 분석이 필요하고, 무조건 배당률만 보고 사면 위험해요. ETF로 분산투자하는 게 개별 종목보다 안전한 것 같아요. ${D}`,
    pros: "꾸준한 현금 흐름",
    cons: "주가 하락 시 총수익 마이너스 가능",
    recommend: true,
  },

  // ── ETF 적립식 투자 ──
  {
    nickname: "ETF매달적립중",
    hustle_id: "etf-investing",
    hustle_name: "ETF 적립식 투자",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 2,
    satisfaction: 4,
    title: "S&P500 ETF 3년 적립, 수익률 50%",
    content: `매달 30만원씩 S&P500 ETF 3년 적립했는데 수익률 50% 됐어요. 절대 금액은 540만원 수익이에요. 시장 하락해도 계속 사는 게 핵심이고 멘탈 관리가 제일 중요해요. 부업이라기보다 자산 형성 수단인데, 가장 손쉬운 부자 되는 방법 같아요. 10년 20년 장기로 가야 빛납니다. ${D}`,
    pros: "간편한 투자, 장기 우상향 기대",
    cons: "단기 수익 없음, 원금 손실 가능성",
    recommend: true,
  },
  {
    nickname: "ETF초보자",
    hustle_id: "etf-investing",
    hustle_name: "ETF 적립식 투자",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 2,
    satisfaction: 3,
    title: "투자 시작했는데 단기 수익 없어서 답답해요",
    content: `ETF 적립식 투자 1년 됐는데 수익률 8%예요. 월 20만원 투자해서 1년에 19만원 수익이라 체감이 별로 없어요. 복리 효과는 10년 후에 나타난다고 하는데 당장 수익이 필요한 분께는 답답할 수 있어요. 부업보다는 저축 대체 개념으로 접근하는 게 맞는 것 같아요. ${D}`,
    pros: "자동화 투자 가능, 세계 최고 기업들에 분산투자",
    cons: "단기 체감 수익 없음, 원금 손실 가능",
    recommend: true,
  },

  // ── 코인 투자 ──
  {
    nickname: "코인대박경험자",
    hustle_id: "crypto",
    hustle_name: "코인 투자",
    income_range: "over_100",
    weekly_hours: 3,
    difficulty: 4,
    satisfaction: 3,
    title: "상승장엔 월 200만원 수익, 하락장엔 반토막",
    content: `비트코인, 이더리움 비중 투자로 상승장에 월 200만원+ 수익 본 적 있어요. 근데 하락장에 50% 빠지는 걸 버텨내는 게 정말 힘들어요. 코인은 수익이 날 때 일부 현금화하고 여유 자금만 넣는 게 원칙이에요. 레버리지는 절대 하지 마세요. 대박도 있지만 쪽박도 있어요. ${D}`,
    pros: "상승장엔 빠른 고수익",
    cons: "변동성 극심, 심리적 스트레스 큼",
    recommend: false,
  },
  {
    nickname: "코인손절한사람",
    hustle_id: "crypto",
    hustle_name: "코인 투자",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 4,
    satisfaction: 1,
    title: "알트코인에 500만원 넣었다가 90% 날렸어요",
    content: `SNS에서 추천받은 알트코인에 500만원 투자했다가 450만원 날렸어요. 비트코인 외 알트코인은 변동성이 너무 심하고 펀더멘털 없는 코인들이 많아요. 부업으로 코인 하려면 비트코인, 이더리움만 소액으로 장기 투자하는 것 외엔 권장하지 않아요. 절대 여유 자금 외 투자 금지입니다. ${D}`,
    pros: "비트코인 장기투자는 역사적으로 우상향",
    cons: "알트코인 손실 위험 극심, 사기 프로젝트 많음",
    recommend: false,
  },

  // ── P2P 투자 ──
  {
    nickname: "P2P투자중",
    hustle_id: "p2p-lending",
    hustle_name: "P2P 투자 (피플펀드 등)",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 2,
    satisfaction: 3,
    title: "연 8% 이자 수익, 소액으로 분산 투자 중",
    content: `피플펀드에서 소액 분산 투자 중이에요. 연 7~9% 수익 기대하고 100만원 투자해서 연 7~9만원 이자 받아요. 부동산 담보 채권이 많아서 상대적으로 안전하다고 하지만 원금 손실 가능성도 있어요. 분산 투자가 필수고, 한 채권에 크게 넣으면 안 돼요. ${D}`,
    pros: "예금보다 높은 금리, 소액 분산 투자 가능",
    cons: "원금 손실 가능, 유동성 없음",
    recommend: true,
  },
  {
    nickname: "P2P손실경험자",
    hustle_id: "p2p-lending",
    hustle_name: "P2P 투자 (피플펀드 등)",
    income_range: "under_10",
    weekly_hours: 1,
    difficulty: 2,
    satisfaction: 2,
    title: "연체·부도로 원금 일부 못 돌려받았어요",
    content: `P2P 투자하다가 채권 연체로 원금 30% 돌려받지 못했어요. 금리가 높다는 건 그만큼 리스크가 있다는 의미인데 처음엔 몰랐어요. 플랫폼마다 신뢰도 차이가 있고, 금융위원회 등록 여부 꼭 확인해야 해요. 지금은 정부 보증 상품 위주로 바꿨어요. ${D}`,
    pros: "운용 간편",
    cons: "원금 손실 가능, 연체 위험 있음",
    recommend: false,
  },

  // ── 배달의민족 라이더 ──
  {
    nickname: "배민라이더5년",
    hustle_id: "baemin-rider",
    hustle_name: "배달의민족 라이더",
    income_range: "over_100",
    weekly_hours: 20,
    difficulty: 2,
    satisfaction: 4,
    title: "주말 저녁만 나가도 월 80만원 추가 수입",
    content: `오토바이로 배민 라이더 주말 저녁 4~5시간씩 나가고 있어요. 금요일·토요일 저녁은 콜이 많아서 시간당 2~2.5만원 수익이 나와요. 주말만 해도 월 70~90만원 추가 수입이에요. 날씨 나쁘면 힘들고 사고 위험이 있지만, 시간 대비 수익은 확실해요. ${D}`,
    pros: "높은 시간당 수익, 원하는 시간에만 가능",
    cons: "날씨 영향, 사고 위험, 체력 소모",
    recommend: true,
  },
  {
    nickname: "배민라이더현실",
    hustle_id: "baemin-rider",
    hustle_name: "배달의민족 라이더",
    income_range: "30_to_50",
    weekly_hours: 15,
    difficulty: 2,
    satisfaction: 3,
    title: "수익은 나오는데 체력 소모가 생각보다 심해요",
    content: `배민 라이더 6개월 했는데 수익은 월 40만원 나오는데 체력 소모가 심해요. 오토바이 타는 게 처음엔 재밌었는데 더운 여름, 추운 겨울엔 정말 힘들어요. 비·눈 올 때도 나가야 수입이 나오는데 그때가 가장 힘들어요. 오토바이 유지비, 기름값도 빠져요. ${D}`,
    pros: "현금 수입 즉시",
    cons: "체력 소모, 계절 날씨 영향, 사고 위험",
    recommend: true,
  },

  // ── 쿠팡플렉스 ──
  {
    nickname: "쿠팡플렉스새벽배송",
    hustle_id: "coupang-flex",
    hustle_name: "쿠팡플렉스",
    income_range: "30_to_50",
    weekly_hours: 20,
    difficulty: 2,
    satisfaction: 3,
    title: "새벽 5시간에 6~7만원, 체력만 되면 추천",
    content: `쿠팡플렉스 새벽 2시~7시 배송 주 3회 하고 있어요. 한 번 나가면 5~7만원 수익이에요. 한 달 12회 나가면 60~80만원인데 새벽이라 수면이 가장 힘든 부분이에요. 차에 짐 싣고 혼자 배송하는 거라 어렵진 않아요. 새벽 시간 활용하는 분들에게 현실적인 부업이에요. ${D}`,
    pros: "새벽 유휴 시간 활용, 비교적 안정적 수익",
    cons: "새벽 수면 패턴 망가짐, 체력 소모",
    recommend: true,
  },
  {
    nickname: "쿠팡플렉스경험자",
    hustle_id: "coupang-flex",
    hustle_name: "쿠팡플렉스",
    income_range: "10_to_30",
    weekly_hours: 10,
    difficulty: 2,
    satisfaction: 2,
    title: "시간 대비 수익 계산하면 높지 않아요",
    content: `쿠팡플렉스 해봤는데 배송 구역마다 건수 차이가 심해요. 운 좋은 날은 5시간에 7만원, 운 나쁜 날은 4만원이에요. 기름값, 차량 마모 감안하면 순수익이 생각보다 낮아요. 주차 문제, 아파트 엘리베이터 기다리는 시간도 은근히 많아요. 단순 부업으론 괜찮지만 마냥 쉽지는 않아요. ${D}`,
    pros: "즉시 시작 가능, 차량 있으면 바로",
    cons: "차량 유지비 감안 시 실수익 낮음, 새벽 체력 소모",
    recommend: false,
  },

  // ── 카카오T 대리운전 ──
  {
    nickname: "대리기사5년차",
    hustle_id: "kakao-driver",
    hustle_name: "카카오T 대리운전",
    income_range: "over_100",
    weekly_hours: 20,
    difficulty: 2,
    satisfaction: 4,
    title: "주 5일 저녁 4시간에 월 순수익 180만원",
    content: `카카오T 대리 5년 넘게 하고 있어요. 금요일~일요일이 콜이 많고 시간당 2.5~3만원 수익이에요. 평일도 저녁 4시간 나가면 8~10만원 나오고 월 180만원 순수익이에요. 대리 보험 필수고 초반엔 지역 파악이 필요해요. 술자리 손님 대응이 가끔 힘들지만 대부분 괜찮아요. ${D}`,
    pros: "높은 시간당 수익, 저녁 시간 활용",
    cons: "늦은 귀가, 취객 대응 스트레스",
    recommend: true,
  },
  {
    nickname: "대리운전시작함",
    hustle_id: "kakao-driver",
    hustle_name: "카카오T 대리운전",
    income_range: "50_to_100",
    weekly_hours: 12,
    difficulty: 2,
    satisfaction: 4,
    title: "보험 가입 후 바로 시작, 월 60만원 용돈",
    content: `대리운전 보험 가입하고 카카오T 등록해서 시작했어요. 초반에 지역 파악이 좀 걸렸는데 1~2주 지나니까 익숙해졌어요. 주 2~3회 저녁 나가서 월 55~65만원 수익이에요. 생각보다 간단하고 운전 좋아하는 분들에게 추천해요. 직접 복귀는 대중교통이라 대기 시간이 있어요. ${D}`,
    pros: "즉시 시작 가능, 높은 시간당 수익",
    cons: "귀가 교통비·시간, 야간 활동",
    recommend: true,
  },

  // ── 킥보드 충전 ──
  {
    nickname: "킥보드충전러",
    hustle_id: "kick-charge",
    hustle_name: "킥보드 충전 (라임·씽씽)",
    income_range: "under_10",
    weekly_hours: 8,
    difficulty: 1,
    satisfaction: 2,
    title: "밤에 킥보드 줍는 게 은근히 힘들어요",
    content: `라임 킥보드 충전해봤는데 생각보다 힘들어요. 밤에 킥보드 위치 찾아다니고 집에 옮겨서 충전하고 새벽에 배치하러 나가야 해요. 건당 1500~3000원인데 한 번에 3~5대 해도 1만원 내외에요. 차 없이는 하기 힘들고 차 있으면 기름값이 수익 잡아먹어요. ${D}`,
    pros: "즉시 시작 가능, 야간 활동",
    cons: "수익 너무 낮음, 차량 필요, 체력 소모",
    recommend: false,
  },
  {
    nickname: "씽씽충전자",
    hustle_id: "kick-charge",
    hustle_name: "킥보드 충전 (라임·씽씽)",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 1,
    satisfaction: 2,
    title: "킥보드 많은 지역에 살아야 의미있어요",
    content: `씽씽 충전 3개월 해봤는데 서울 도심 거주자가 아니면 수익이 너무 낮아요. 킥보드가 많은 지역이라야 모으는 효율이 올라가는데 제 사는 곳엔 별로 없어서 월 3~5만원 수준이에요. 킥보드 많은 지역 거주자에겐 그나마 낫겠지만 시급은 낮아요. ${D}`,
    pros: "진입장벽 없음",
    cons: "지역 편차 심함, 수익 낮음",
    recommend: false,
  },

  // ── 전자책 출판 ──
  {
    nickname: "전자책월300만",
    hustle_id: "ebook",
    hustle_name: "전자책 출판",
    income_range: "over_100",
    weekly_hours: 5,
    difficulty: 2,
    satisfaction: 5,
    title: "부업 노하우 전자책 월 150만원 패시브 수익",
    content: `N잡 노하우 전자책을 크몽에서 판매 중이에요. PDF 50페이지 만들어서 가격 2만 9900원에 팔고 있는데 월 50~60건 팔려요. 처음 만들 때 2주 걸렸는데 이후엔 손댈 게 없어요. 완전한 패시브 인컴이에요. 경험이나 전문 지식 있으면 누구나 도전할 수 있어요. ${D}`,
    pros: "제작 후 완전 패시브 수익, 비용 거의 없음",
    cons: "초기 제작 시간 투자, 홍보 없으면 판매 안 됨",
    recommend: true,
  },
  {
    nickname: "전자책판매중",
    hustle_id: "ebook",
    hustle_name: "전자책 출판",
    income_range: "10_to_30",
    weekly_hours: 3,
    difficulty: 2,
    satisfaction: 3,
    title: "만들긴 했는데 홍보 안 하면 안 팔려요",
    content: `다이어트 식단 전자책 만들어서 올렸는데 처음엔 한 달에 2~3건밖에 안 팔렸어요. 인스타 계정 키우고 홍보하기 시작하니 월 10~15건으로 늘었고 20~25만원 수익이에요. 전자책 자체보다 홍보 채널이 더 중요한 것 같아요. 채널 있는 분들이 훨씬 유리해요. ${D}`,
    pros: "패시브 인컴 가능",
    cons: "홍보 없으면 판매 안 됨, 채널 필수",
    recommend: true,
  },

  // ── 노션 템플릿 판매 ──
  {
    nickname: "노션템플릿셀러",
    hustle_id: "notion-template",
    hustle_name: "노션 템플릿 판매",
    income_range: "10_to_30",
    weekly_hours: 3,
    difficulty: 2,
    satisfaction: 4,
    title: "노션 다이어리 템플릿으로 월 20만원 패시브",
    content: `크몽에 노션 연간 플래너 템플릿 올렸어요. 9900원짜리인데 월 20~25건 팔려요. 처음 만들 때 하루 걸렸고 이후 수정 거의 없어요. 노션 관심 있고 UI 감각 있으면 누구나 만들 수 있어요. Gumroad에도 올리면 해외 판매도 돼서 수익이 더 늘었어요. ${D}`,
    pros: "제작 쉬움, 패시브 수익",
    cons: "개당 가격 낮음, 많이 팔아야 의미있는 수익",
    recommend: true,
  },
  {
    nickname: "노션템플릿만들어봄",
    hustle_id: "notion-template",
    hustle_name: "노션 템플릿 판매",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 2,
    satisfaction: 3,
    title: "만들기는 쉬운데 경쟁자가 많아요",
    content: `노션 습관 추적 템플릿 만들어서 크몽에 올렸는데 비슷한 템플릿이 이미 많이 있어요. 차별화 안 되면 잘 안 팔려요. 3개월에 15건 판매해서 4만원 수익이에요. 독특한 아이디어나 니치한 주제 템플릿이 더 잘 팔리는 것 같아요. 홍보 없이는 한계가 있어요. ${D}`,
    pros: "제작 비용 없음",
    cons: "경쟁 많음, 차별화 필수, 단독으론 수익 낮음",
    recommend: false,
  },

  // ── 스톡 사진 판매 ──
  {
    nickname: "스톡사진작가",
    hustle_id: "stock-photo",
    hustle_name: "스톡 사진·영상 판매",
    income_range: "10_to_30",
    weekly_hours: 5,
    difficulty: 3,
    satisfaction: 4,
    title: "사진 300장 올리니 월 15만원 자동으로 들어와요",
    content: `어도비스톡, 셔터스톡에 사진 300장 올렸어요. 일상 사진이나 음식 사진 위주인데 매달 자동으로 15만원 들어와요. 한 장당 수익은 적지만 장수가 쌓이면 패시브 수익이 돼요. 카메라 있고 사진 찍기 좋아하는 분들에게 강추예요. 처음엔 승인 거절도 많지만 기준 파악하면 수월해요. ${D}`,
    pros: "패시브 수익, 사진 취미와 수익 병행",
    cons: "초반 사진 수 쌓기 필요, 승인 기준 엄격",
    recommend: true,
  },
  {
    nickname: "스톡영상판매자",
    hustle_id: "stock-photo",
    hustle_name: "스톡 사진·영상 판매",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 3,
    satisfaction: 3,
    title: "사진보다 영상이 단가 높은데 제작이 어려워요",
    content: `스톡 영상이 사진보다 단가 5~10배 높다고 해서 도전해봤는데 승인 기준이 훨씬 엄격해요. 흔들림, 노이즈 하나라도 있으면 거절돼요. 영상 50개 올려서 월 5~8만원 수익이에요. 전문 장비 없이는 승인 받기 어렵고, 초보엔 사진부터 시작 권장합니다. ${D}`,
    pros: "영상 단가 높음",
    cons: "영상 승인 기준 엄격, 전문 장비 필요",
    recommend: false,
  },

  // ── AI 프롬프트 판매 ──
  {
    nickname: "AI프롬프트셀러",
    hustle_id: "ai-prompt",
    hustle_name: "AI 프롬프트 판매",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 2,
    satisfaction: 3,
    title: "Promptbase에서 미드저니 프롬프트 월 8만원",
    content: `Midjourney용 아트 프롬프트 30개 Promptbase에 올렸어요. 개당 $3~$5에 팔리는데 월 $50~$70 수익이에요. 처음엔 잘 안 팔렸는데 미리보기 이미지 퀄리티 높이니 판매가 늘었어요. 크몽에서도 ChatGPT 프롬프트 팔면 건당 1~3만원 받아요. 아직 시장이 크진 않지만 성장 중인 분야예요. ${D}`,
    pros: "제작 비용 없음, 성장하는 시장",
    cons: "아직 시장 규모 작음, 수익 낮음",
    recommend: true,
  },
  {
    nickname: "프롬프트도전자",
    hustle_id: "ai-prompt",
    hustle_name: "AI 프롬프트 판매",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 2,
    satisfaction: 2,
    title: "AI 도구 보급되면서 프롬프트 가치가 낮아지는 것 같아요",
    content: `챗GPT 프롬프트 팔아봤는데 AI가 워낙 좋아져서 사람들이 직접 만드는 경우가 많아져요. 처음엔 팔렸는데 점점 판매가 줄어드는 추세예요. 아직 초기 시장이긴 하지만 장기적으로 경쟁이 심해질 것 같아요. 지금 당장 큰 수익은 어렵지만 니치한 분야 프롬프트는 여전히 팔려요. ${D}`,
    pros: "시작 비용 없음",
    cons: "AI 발전으로 가치 하락 우려, 경쟁 심화",
    recommend: false,
  },

  // ── BGM 음악 판매 ──
  {
    nickname: "BGM음악판매자",
    hustle_id: "bgm-music",
    hustle_name: "BGM·음악 판매 (AudioJungle)",
    income_range: "10_to_30",
    weekly_hours: 8,
    difficulty: 4,
    satisfaction: 4,
    title: "AudioJungle에 BGM 50곡, 월 $150 패시브",
    content: `유튜브 배경음악용 BGM 50곡 AudioJungle에 올렸어요. 월 $100~$200 자동 수익이에요. 음악 1곡 만드는 데 2~3시간 걸리지만 이후 계속 팔려요. 처음 몇 곡은 승인 거절도 많았는데 스타일 파악하고 나서 승인율 올랐어요. 음악 제작 능력 있으면 진짜 좋은 패시브 인컴이에요. ${D}`,
    pros: "패시브 수익, 음악 스킬 활용",
    cons: "음악 제작 능력 필수, 승인 기준 있음",
    recommend: true,
  },
  {
    nickname: "음악취미로부업",
    hustle_id: "bgm-music",
    hustle_name: "BGM·음악 판매 (AudioJungle)",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 4,
    satisfaction: 3,
    title: "취미로 만든 음악이지만 승인 기준이 꽤 높아요",
    content: `FL Studio로 음악 취미로 하다가 AudioJungle 도전했는데 초반에 10곡 중 7곡이 거절됐어요. 음질 기준이 생각보다 엄격해요. 지금은 15곡 승인 받았는데 월 $30 수준이에요. 장기적으로 곡 수 쌓으면 의미있겠지만 현재는 소액이에요. ${D}`,
    pros: "음악 취미와 수익 병행",
    cons: "승인 기준 엄격, 초반 수익 미미",
    recommend: true,
  },

  // ── Figma 템플릿 판매 ──
  {
    nickname: "피그마템플릿작가",
    hustle_id: "figma-template",
    hustle_name: "Figma·PPT 템플릿 판매",
    income_range: "10_to_30",
    weekly_hours: 5,
    difficulty: 3,
    satisfaction: 4,
    title: "Creative Market에 PPT 템플릿 월 $100",
    content: `Creative Market에 PPT 프레젠테이션 템플릿 20개 올렸어요. 개당 $15~$25에 팔리는데 월 $80~$120 수익이에요. 템플릿 하나 만드는 데 4~6시간 걸리지만 이후 계속 팔려요. 디자이너가 아니어도 Canva로 깔끔한 템플릿 만들면 팔려요. 영어로 판매하면 전 세계 고객이 생겨요. ${D}`,
    pros: "달러 패시브 수익, 글로벌 고객",
    cons: "초기 템플릿 제작 시간 투자",
    recommend: true,
  },
  {
    nickname: "캔바템플릿팔기",
    hustle_id: "figma-template",
    hustle_name: "Figma·PPT 템플릿 판매",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 3,
    satisfaction: 3,
    title: "크몽에서 Canva 템플릿 팔고 있어요",
    content: `Canva 소셜미디어 템플릿 크몽에 올렸는데 개당 3000~5000원에 팔려요. 월 판매 10~15건으로 4~6만원 수익이에요. 단가가 낮아서 판매량 많이 키워야 의미있는 수익이 돼요. 국내 크몽보다 해외 Gumroad나 Creative Market이 단가 높은 것 같아요. ${D}`,
    pros: "제작 쉬움, 패시브 수익",
    cons: "국내 단가 낮음, 해외 플랫폼이 더 유리",
    recommend: true,
  },

  // ── E심팔이 ──
  {
    nickname: "이심팔이운영자",
    hustle_id: "esim-palee",
    hustle_name: "E심팔이 (eSIM 재판매)",
    income_range: "30_to_50",
    weekly_hours: 5,
    difficulty: 2,
    satisfaction: 4,
    title: "여행 시즌에 eSIM 판매로 월 40만원",
    content: `eSIM 도매 플랫폼에서 구매해서 인스타, 카카오톡 채널로 판매 중이에요. 일본, 유럽 eSIM 수요가 많고 건당 마진 3000~8000원인데 성수기(여름, 추석, 설날)엔 하루 10~20건 팔려요. 월 평균 35~45만원 수익이에요. 고객 응대만 잘하면 재구매율이 높아서 자동화 느낌으로 운영돼요. ${D}`,
    pros: "자동화 가능, 여행 수요 꾸준함",
    cons: "성수기·비수기 수익 편차, 초기 채널 구축 필요",
    recommend: true,
  },
  {
    nickname: "이심부업시작",
    hustle_id: "esim-palee",
    hustle_name: "E심팔이 (eSIM 재판매)",
    income_range: "under_10",
    weekly_hours: 3,
    difficulty: 2,
    satisfaction: 3,
    title: "채널 없으면 판매처가 없어서 힘들어요",
    content: `eSIM 판매 시작했는데 홍보 채널이 없으니 판매가 안 돼요. 인스타나 블로그 기반이 있어야 의미있는 수익이 나오는 구조예요. 채널 있는 분들에겐 괜찮은 부업이지만 채널 없이 시작하면 막막해요. 오픈채팅방으로 시작하는 방법도 있긴 해요. ${D}`,
    pros: "진입 비용 적음",
    cons: "채널 없으면 판매처 없음, 경쟁 심화 추세",
    recommend: false,
  },

  // ── 릴픽스 ──
  {
    nickname: "릴픽스편집자",
    hustle_id: "reelfix",
    hustle_name: "릴픽스",
    income_range: "30_to_50",
    weekly_hours: 15,
    difficulty: 3,
    satisfaction: 4,
    title: "숏폼 편집으로 릴픽스 월 35만원",
    content: `영상 편집 배운 지 3개월 됐는데 릴픽스에서 릴스·쇼츠 편집 맡고 있어요. 건당 3~5만원이고 월 8~10건 소화하면 35만원 수익이에요. 편집 속도 올리는 게 수익과 직결되는데 빨라질수록 시급이 올라가요. 숏폼 편집 수요가 계속 늘어서 기회가 많아요. ${D}`,
    pros: "숏폼 편집 수요 증가, 재택 가능",
    cons: "편집 스킬 필요, 빠른 납기 요구",
    recommend: true,
  },
  {
    nickname: "영상편집부업중",
    hustle_id: "reelfix",
    hustle_name: "릴픽스",
    income_range: "10_to_30",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 3,
    title: "건당 단가가 낮아서 많이 해야 수익이 나요",
    content: `릴픽스에서 숏폼 편집 3개월 했는데 건당 2~3만원 수준이에요. 10분짜리 영상 편집에 2시간 걸리면 시급 1~1.5만원인데 그다지 높지 않아요. 편집 실력 올리면서 단가 높은 클라이언트 찾는 게 목표예요. 크몽에서 더 높은 단가로 받을 수도 있어요. ${D}`,
    pros: "수요 많음, 재택 가능",
    cons: "초보 단가 낮음, 속도 빨라야 시급 나옴",
    recommend: true,
  },

  // ── AI 자동화 서비스 판매 ──
  {
    nickname: "AI서비스판매자",
    hustle_id: "chatgpt-service",
    hustle_name: "AI 자동화 서비스 판매",
    income_range: "over_100",
    weekly_hours: 15,
    difficulty: 3,
    satisfaction: 5,
    title: "ChatGPT 자동화 컨설팅으로 건당 50만원",
    content: `중소기업 대상으로 ChatGPT 업무 자동화 컨설팅 크몽에서 팔고 있어요. 마케팅 문구 자동화, 보고서 생성, 고객 응대 챗봇 구축 등의 서비스를 건당 30~80만원에 팔아요. 월 2~3건이면 100만원 이상이에요. AI에 대한 기업 관심이 높아서 문의가 계속 들어와요. ${D}`,
    pros: "높은 단가, AI 수요 폭발적 증가",
    cons: "AI 기술 지속 학습 필요, 경쟁 심화 추세",
    recommend: true,
  },
  {
    nickname: "AI부업입문자",
    hustle_id: "chatgpt-service",
    hustle_name: "AI 자동화 서비스 판매",
    income_range: "10_to_30",
    weekly_hours: 8,
    difficulty: 3,
    satisfaction: 3,
    title: "소규모 AI 서비스로 월 20만원 시작",
    content: `챗GPT로 블로그 글 자동화 서비스 크몽에 올렸어요. 건당 5~10만원인데 월 2~4건 들어와요. 아직 수익이 크지 않은데 AI 기술 더 익히면서 단가 높이는 중이에요. 이 분야는 빠르게 성장하고 있어서 지금 준비하면 나중에 유리할 것 같아요. ${D}`,
    pros: "성장하는 시장, 기술 문턱 낮아지는 중",
    cons: "AI 빠른 발전으로 서비스 차별화 어려움",
    recommend: true,
  },

  // ── 번역 프리랜서 ──
  {
    nickname: "번역가프리랜서",
    hustle_id: "translation",
    hustle_name: "번역 프리랜서 (플리토 등)",
    income_range: "50_to_100",
    weekly_hours: 12,
    difficulty: 3,
    satisfaction: 4,
    title: "IT 전문 번역으로 크몽 월 65만원",
    content: `IT 분야 영한 번역 크몽에서 하고 있어요. 일반 번역보다 IT 전문 번역이 단가 2~3배 높아요. 건당 5~15만원이고 월 5~8건 정도 소화해서 65만원 수익이에요. 초반에 포트폴리오 만드느라 저단가로 일했는데 지금은 일감이 꾸준히 들어와요. 영어 잘하면 진짜 좋은 부업이에요. ${D}`,
    pros: "전문 분야 고단가, 재택 가능",
    cons: "전문 번역 지식 필요, 초반 포트폴리오 쌓기 필요",
    recommend: true,
  },
  {
    nickname: "번역알바중",
    hustle_id: "translation",
    hustle_name: "번역 프리랜서 (플리토 등)",
    income_range: "10_to_30",
    weekly_hours: 6,
    difficulty: 3,
    satisfaction: 3,
    title: "플리토는 단가가 너무 낮아요",
    content: `플리토에서 번역 알바 해봤는데 단가가 너무 낮아요. 100자 번역에 200~500원 수준인데 시급 계산하면 최저시급도 안 돼요. 크몽 같은 플랫폼에서 직접 서비스를 팔거나 직접 클라이언트 찾는 게 수익이 훨씬 높아요. 플리토는 번역 연습용으로만 활용하는 게 낫겠어요. ${D}`,
    pros: "번역 연습 가능",
    cons: "플리토 단가 매우 낮음, 시급 낮음",
    recommend: false,
  },

  // ── 가상 비서 ──
  {
    nickname: "가상비서운영자",
    hustle_id: "virtual-assistant",
    hustle_name: "가상 비서 (VA) 서비스",
    income_range: "50_to_100",
    weekly_hours: 15,
    difficulty: 2,
    satisfaction: 4,
    title: "해외 스타트업 VA로 시간당 $20 받아요",
    content: `업워크에서 해외 스타트업 가상 비서 일 맡고 있어요. 이메일 응대, 일정 관리, 리서치 작업인데 시간당 $20 받아요. 영어 커뮤니케이션 능숙하면 국내보다 2~3배 높은 단가를 받을 수 있어요. 월 주 3일 일해서 75만원 수익이에요. 재택이고 시간 유연해서 본업과 병행하기 좋아요. ${D}`,
    pros: "재택, 시간 유연, 해외 고객 시 고단가",
    cons: "영어 필수, 초반 클라이언트 찾기 어려움",
    recommend: true,
  },
  {
    nickname: "국내VA도전자",
    hustle_id: "virtual-assistant",
    hustle_name: "가상 비서 (VA) 서비스",
    income_range: "under_10",
    weekly_hours: 8,
    difficulty: 2,
    satisfaction: 2,
    title: "국내 VA는 단가가 낮고 잡일이 많아요",
    content: `국내 소규모 기업 가상 비서 일 해봤는데 단가가 시간당 1만원 수준이에요. 하는 일은 엑셀 정리, SNS 관리, 전화 응대 대행 등인데 범위가 계속 늘어나는 경향이 있어요. 월 8만원 수익인데 투자 시간 대비 낮아요. 해외 클라이언트 찾는 게 훨씬 낫겠다고 생각했어요. ${D}`,
    pros: "진입장벽 낮음",
    cons: "국내 단가 낮음, 업무 범위 무제한 늘어남",
    recommend: false,
  },

  // ── NFT 판매 ──
  {
    nickname: "NFT아티스트",
    hustle_id: "nft",
    hustle_name: "NFT 제작·판매",
    income_range: "under_10",
    weekly_hours: 5,
    difficulty: 4,
    satisfaction: 2,
    title: "NFT 시장 침체로 거의 판매 안 돼요",
    content: `디지털 아트 NFT OpenSea에 올렸는데 2023년 이후 거의 판매가 없어요. 가스비만 날렸어요. NFT 시장 자체가 많이 침체됐고, 유명인이 아닌 이상 판매하기 너무 힘든 구조예요. 지금은 그냥 NFT 포트폴리오 쌓는 용도로만 올리고 있어요. 수익화 기대는 내려놨어요. ${D}`,
    pros: "독창적 아트워크 영구 기록",
    cons: "시장 침체, 가스비 손실 가능, 판매 거의 없음",
    recommend: false,
  },
  {
    nickname: "NFT포기선언",
    hustle_id: "nft",
    hustle_name: "NFT 제작·판매",
    income_range: "under_10",
    weekly_hours: 2,
    difficulty: 4,
    satisfaction: 1,
    title: "2021년엔 대박, 지금은 시장이 죽었어요",
    content: `2021년 NFT 열풍 때 픽셀 아트 NFT로 수익 좀 봤는데, 지금은 시장이 완전히 꺼진 느낌이에요. OpenSea 거래량이 최고점 대비 99% 감소했다는 통계도 있어요. 지금 시작하는 건 권장하지 않아요. 디지털 아트는 다른 채널로 수익화하는 게 나아요. ${D}`,
    pros: "과거엔 고수익 가능했음",
    cons: "시장 사실상 붕괴, 진입 비추",
    recommend: false,
  },

  // ── 게임 대리육성·코칭 ──
  {
    nickname: "롤코치중",
    hustle_id: "game-boosting",
    hustle_name: "게임 대리육성·코칭",
    income_range: "10_to_30",
    weekly_hours: 10,
    difficulty: 3,
    satisfaction: 4,
    title: "롤 다이아 코치로 게임코치온라인 월 20만원",
    content: `게임코치온라인에서 롤 1:1 코칭 서비스 하고 있어요. 시간당 2~3만원 받고 월 7~8회 코칭하면 20만원 정도예요. 대리육성은 계정 정지 위험이 있어서 코칭으로 합법적으로 하고 있어요. 게임 잘 하면서 설명도 잘 해야 좋은 리뷰 받아요. 게임 좋아하면 재미있게 할 수 있는 부업이에요. ${D}`,
    pros: "게임 취미와 수익 병행, 합법적 방법 있음",
    cons: "고티어 실력 필요, 설명 능력도 필요",
    recommend: true,
  },
  {
    nickname: "게임대리경험자",
    hustle_id: "game-boosting",
    hustle_name: "게임 대리육성·코칭",
    income_range: "under_10",
    weekly_hours: 6,
    difficulty: 3,
    satisfaction: 2,
    title: "대리는 계정 정지 위험 있어서 그만뒀어요",
    content: `예전에 롤 대리육성 해봤는데 계정 정지 리스크가 있어서 그만뒀어요. 건당 2~5만원 수익인데 들키면 의뢰인 계정도 정지되고 법적으로도 문제될 수 있어요. 코칭 플랫폼으로 합법적으로 하는 게 맞는데, 코칭은 실력 설명 능력이 함께 필요해서 진입장벽이 높아요. ${D}`,
    pros: "게임 실력 있으면 수익 가능",
    cons: "대리육성은 법적·약관 위반, 코칭은 설명 능력 필요",
    recommend: false,
  },
];

async function insertReviews() {
  console.log(`총 ${reviews.length}개 후기 삽입 시작...`);

  let successCount = 0;
  let errorCount = 0;

  for (const review of reviews) {
    const { error } = await supabase.from("reviews").insert({
      nickname: review.nickname,
      hustle_id: review.hustle_id,
      hustle_name: review.hustle_name,
      income_range: review.income_range,
      weekly_hours: review.weekly_hours,
      difficulty: review.difficulty,
      satisfaction: review.satisfaction,
      title: review.title,
      content: review.content,
      pros: review.pros,
      cons: review.cons,
      recommend: review.recommend,
      likes: 0,
      proof_image_url: null,
      kakao_user_id: null,
    });

    if (error) {
      console.error(`❌ 오류 [${review.hustle_id}]:`, error.message);
      errorCount++;
    } else {
      console.log(`✅ 삽입 완료: [${review.hustle_id}] ${review.title}`);
      successCount++;
    }
  }

  console.log(`\n완료: 성공 ${successCount}건, 실패 ${errorCount}건`);
}

insertReviews();
